package com.cetcme.springBootDemo.mapper;

import com.cetcme.springBootDemo.domain.Alarm;
import com.cetcme.springBootDemo.domain.AlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int countByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long alarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int insert(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int insertSelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    List<Alarm> selectByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    Alarm selectByPrimaryKey(Long alarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Alarm record);
}