package com.cetcme.springBootDemo.mapper;

import com.cetcme.springBootDemo.domain.Circle;

public interface CircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long circleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    int insert(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    int insertSelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    Circle selectByPrimaryKey(Long circleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Circle record);
}