package com.cetcme.springBootDemo.mapper;

import com.cetcme.springBootDemo.domain.Command;
import com.cetcme.springBootDemo.domain.CommandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommandMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int countByExample(CommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long commandId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int insert(Command record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int insertSelective(Command record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	List<Command> selectByExample(CommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	Command selectByPrimaryKey(Long commandId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Command record, @Param("example") CommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Command record, @Param("example") CommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Command record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_command
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Command record);

	int insertBatch(List<Command> commandList);
}