package com.cetcme.springBootDemo.mapper;

import com.cetcme.springBootDemo.domain.Dict;
import com.cetcme.springBootDemo.domain.DictExample;
import java.util.List;

public interface DictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    int insert(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    int insertSelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    List<Dict> selectByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    Dict selectByPrimaryKey(Long dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dict record);
}