package com.cetcme.springBootDemo.mapper;

import com.cetcme.springBootDemo.domain.IofLog;
import com.cetcme.springBootDemo.domain.IofLogExample;
import java.util.List;

public interface IofLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long iofLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    int insert(IofLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    int insertSelective(IofLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    List<IofLog> selectByExample(IofLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    IofLog selectByPrimaryKey(Long iofLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IofLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IofLog record);
}