package com.cetcme.springBootDemo.mapper;

import com.cetcme.springBootDemo.domain.SysConfig;
import com.cetcme.springBootDemo.domain.SysConfigExample;
import java.util.List;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    int insertSelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    List<SysConfig> selectByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    SysConfig selectByPrimaryKey(Long sysConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysConfig record);
}