package com.cetcme.springBootDemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AcqDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public AcqDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAcqDataIdIsNull() {
            addCriterion("`ACQ_DATA_ID` is null");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdIsNotNull() {
            addCriterion("`ACQ_DATA_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdEqualTo(Long value) {
            addCriterion("`ACQ_DATA_ID` =", value, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdNotEqualTo(Long value) {
            addCriterion("`ACQ_DATA_ID` <>", value, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdGreaterThan(Long value) {
            addCriterion("`ACQ_DATA_ID` >", value, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`ACQ_DATA_ID` >=", value, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdLessThan(Long value) {
            addCriterion("`ACQ_DATA_ID` <", value, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdLessThanOrEqualTo(Long value) {
            addCriterion("`ACQ_DATA_ID` <=", value, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdIn(List<Long> values) {
            addCriterion("`ACQ_DATA_ID` in", values, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdNotIn(List<Long> values) {
            addCriterion("`ACQ_DATA_ID` not in", values, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdBetween(Long value1, Long value2) {
            addCriterion("`ACQ_DATA_ID` between", value1, value2, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andAcqDataIdNotBetween(Long value1, Long value2) {
            addCriterion("`ACQ_DATA_ID` not between", value1, value2, "acqDataId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("`DEVICE_ID` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("`DEVICE_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("`DEVICE_ID` =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("`DEVICE_ID` >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("`DEVICE_ID` <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("`DEVICE_ID` in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("`DEVICE_ID` not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIsNull() {
            addCriterion("`DEVICE_NO` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIsNotNull() {
            addCriterion("`DEVICE_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceNoEqualTo(String value) {
            addCriterion("`DEVICE_NO` =", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotEqualTo(String value) {
            addCriterion("`DEVICE_NO` <>", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoGreaterThan(String value) {
            addCriterion("`DEVICE_NO` >", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
            addCriterion("`DEVICE_NO` >=", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLessThan(String value) {
            addCriterion("`DEVICE_NO` <", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLessThanOrEqualTo(String value) {
            addCriterion("`DEVICE_NO` <=", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLike(String value) {
            addCriterion("`DEVICE_NO` like", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotLike(String value) {
            addCriterion("`DEVICE_NO` not like", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIn(List<String> values) {
            addCriterion("`DEVICE_NO` in", values, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotIn(List<String> values) {
            addCriterion("`DEVICE_NO` not in", values, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoBetween(String value1, String value2) {
            addCriterion("`DEVICE_NO` between", value1, value2, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotBetween(String value1, String value2) {
            addCriterion("`DEVICE_NO` not between", value1, value2, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andShipIdIsNull() {
            addCriterion("`SHIP_ID` is null");
            return (Criteria) this;
        }

        public Criteria andShipIdIsNotNull() {
            addCriterion("`SHIP_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andShipIdEqualTo(Long value) {
            addCriterion("`SHIP_ID` =", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotEqualTo(Long value) {
            addCriterion("`SHIP_ID` <>", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdGreaterThan(Long value) {
            addCriterion("`SHIP_ID` >", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`SHIP_ID` >=", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdLessThan(Long value) {
            addCriterion("`SHIP_ID` <", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdLessThanOrEqualTo(Long value) {
            addCriterion("`SHIP_ID` <=", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdIn(List<Long> values) {
            addCriterion("`SHIP_ID` in", values, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotIn(List<Long> values) {
            addCriterion("`SHIP_ID` not in", values, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdBetween(Long value1, Long value2) {
            addCriterion("`SHIP_ID` between", value1, value2, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotBetween(Long value1, Long value2) {
            addCriterion("`SHIP_ID` not between", value1, value2, "shipId");
            return (Criteria) this;
        }

        public Criteria andIofFlagIsNull() {
            addCriterion("`IOF_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andIofFlagIsNotNull() {
            addCriterion("`IOF_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andIofFlagEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` =", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagNotEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` <>", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagGreaterThan(Integer value) {
            addCriterion("`IOF_FLAG` >", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` >=", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagLessThan(Integer value) {
            addCriterion("`IOF_FLAG` <", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagLessThanOrEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` <=", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagIn(List<Integer> values) {
            addCriterion("`IOF_FLAG` in", values, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagNotIn(List<Integer> values) {
            addCriterion("`IOF_FLAG` not in", values, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagBetween(Integer value1, Integer value2) {
            addCriterion("`IOF_FLAG` between", value1, value2, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("`IOF_FLAG` not between", value1, value2, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andAcqTimeIsNull() {
            addCriterion("`ACQ_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andAcqTimeIsNotNull() {
            addCriterion("`ACQ_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andAcqTimeEqualTo(Date value) {
            addCriterion("`ACQ_TIME` =", value, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeNotEqualTo(Date value) {
            addCriterion("`ACQ_TIME` <>", value, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeGreaterThan(Date value) {
            addCriterion("`ACQ_TIME` >", value, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`ACQ_TIME` >=", value, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeLessThan(Date value) {
            addCriterion("`ACQ_TIME` <", value, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeLessThanOrEqualTo(Date value) {
            addCriterion("`ACQ_TIME` <=", value, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeIn(List<Date> values) {
            addCriterion("`ACQ_TIME` in", values, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeNotIn(List<Date> values) {
            addCriterion("`ACQ_TIME` not in", values, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeBetween(Date value1, Date value2) {
            addCriterion("`ACQ_TIME` between", value1, value2, "acqTime");
            return (Criteria) this;
        }

        public Criteria andAcqTimeNotBetween(Date value1, Date value2) {
            addCriterion("`ACQ_TIME` not between", value1, value2, "acqTime");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageIsNull() {
            addCriterion("`DAY_TOTAL_MILEAGE` is null");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageIsNotNull() {
            addCriterion("`DAY_TOTAL_MILEAGE` is not null");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageEqualTo(Double value) {
            addCriterion("`DAY_TOTAL_MILEAGE` =", value, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageNotEqualTo(Double value) {
            addCriterion("`DAY_TOTAL_MILEAGE` <>", value, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageGreaterThan(Double value) {
            addCriterion("`DAY_TOTAL_MILEAGE` >", value, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageGreaterThanOrEqualTo(Double value) {
            addCriterion("`DAY_TOTAL_MILEAGE` >=", value, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageLessThan(Double value) {
            addCriterion("`DAY_TOTAL_MILEAGE` <", value, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageLessThanOrEqualTo(Double value) {
            addCriterion("`DAY_TOTAL_MILEAGE` <=", value, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageIn(List<Double> values) {
            addCriterion("`DAY_TOTAL_MILEAGE` in", values, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageNotIn(List<Double> values) {
            addCriterion("`DAY_TOTAL_MILEAGE` not in", values, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageBetween(Double value1, Double value2) {
            addCriterion("`DAY_TOTAL_MILEAGE` between", value1, value2, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andDayTotalMileageNotBetween(Double value1, Double value2) {
            addCriterion("`DAY_TOTAL_MILEAGE` not between", value1, value2, "dayTotalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageIsNull() {
            addCriterion("`TOTAL_MILEAGE` is null");
            return (Criteria) this;
        }

        public Criteria andTotalMileageIsNotNull() {
            addCriterion("`TOTAL_MILEAGE` is not null");
            return (Criteria) this;
        }

        public Criteria andTotalMileageEqualTo(Double value) {
            addCriterion("`TOTAL_MILEAGE` =", value, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageNotEqualTo(Double value) {
            addCriterion("`TOTAL_MILEAGE` <>", value, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageGreaterThan(Double value) {
            addCriterion("`TOTAL_MILEAGE` >", value, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageGreaterThanOrEqualTo(Double value) {
            addCriterion("`TOTAL_MILEAGE` >=", value, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageLessThan(Double value) {
            addCriterion("`TOTAL_MILEAGE` <", value, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageLessThanOrEqualTo(Double value) {
            addCriterion("`TOTAL_MILEAGE` <=", value, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageIn(List<Double> values) {
            addCriterion("`TOTAL_MILEAGE` in", values, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageNotIn(List<Double> values) {
            addCriterion("`TOTAL_MILEAGE` not in", values, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageBetween(Double value1, Double value2) {
            addCriterion("`TOTAL_MILEAGE` between", value1, value2, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andTotalMileageNotBetween(Double value1, Double value2) {
            addCriterion("`TOTAL_MILEAGE` not between", value1, value2, "totalMileage");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusIsNull() {
            addCriterion("`ALARM_STATUS` is null");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusIsNotNull() {
            addCriterion("`ALARM_STATUS` is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusEqualTo(String value) {
            addCriterion("`ALARM_STATUS` =", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotEqualTo(String value) {
            addCriterion("`ALARM_STATUS` <>", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusGreaterThan(String value) {
            addCriterion("`ALARM_STATUS` >", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`ALARM_STATUS` >=", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusLessThan(String value) {
            addCriterion("`ALARM_STATUS` <", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusLessThanOrEqualTo(String value) {
            addCriterion("`ALARM_STATUS` <=", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusLike(String value) {
            addCriterion("`ALARM_STATUS` like", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotLike(String value) {
            addCriterion("`ALARM_STATUS` not like", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusIn(List<String> values) {
            addCriterion("`ALARM_STATUS` in", values, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotIn(List<String> values) {
            addCriterion("`ALARM_STATUS` not in", values, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusBetween(String value1, String value2) {
            addCriterion("`ALARM_STATUS` between", value1, value2, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotBetween(String value1, String value2) {
            addCriterion("`ALARM_STATUS` not between", value1, value2, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("`LONGITUDE` is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("`LONGITUDE` is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("`LONGITUDE` =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("`LONGITUDE` <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("`LONGITUDE` >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`LONGITUDE` >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("`LONGITUDE` <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("`LONGITUDE` <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("`LONGITUDE` in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("`LONGITUDE` not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("`LONGITUDE` between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("`LONGITUDE` not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("`LATITUDE` is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("`LATITUDE` is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("`LATITUDE` =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("`LATITUDE` <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("`LATITUDE` >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`LATITUDE` >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("`LATITUDE` <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("`LATITUDE` <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("`LATITUDE` in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("`LATITUDE` not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("`LATITUDE` between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("`LATITUDE` not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andSignalTypeIsNull() {
            addCriterion("`SIGNAL_TYPE` is null");
            return (Criteria) this;
        }

        public Criteria andSignalTypeIsNotNull() {
            addCriterion("`SIGNAL_TYPE` is not null");
            return (Criteria) this;
        }

        public Criteria andSignalTypeEqualTo(Integer value) {
            addCriterion("`SIGNAL_TYPE` =", value, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeNotEqualTo(Integer value) {
            addCriterion("`SIGNAL_TYPE` <>", value, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeGreaterThan(Integer value) {
            addCriterion("`SIGNAL_TYPE` >", value, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SIGNAL_TYPE` >=", value, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeLessThan(Integer value) {
            addCriterion("`SIGNAL_TYPE` <", value, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`SIGNAL_TYPE` <=", value, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeIn(List<Integer> values) {
            addCriterion("`SIGNAL_TYPE` in", values, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeNotIn(List<Integer> values) {
            addCriterion("`SIGNAL_TYPE` not in", values, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeBetween(Integer value1, Integer value2) {
            addCriterion("`SIGNAL_TYPE` between", value1, value2, "signalType");
            return (Criteria) this;
        }

        public Criteria andSignalTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`SIGNAL_TYPE` not between", value1, value2, "signalType");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNull() {
            addCriterion("`SPEED` is null");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNotNull() {
            addCriterion("`SPEED` is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedEqualTo(Float value) {
            addCriterion("`SPEED` =", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotEqualTo(Float value) {
            addCriterion("`SPEED` <>", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThan(Float value) {
            addCriterion("`SPEED` >", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThanOrEqualTo(Float value) {
            addCriterion("`SPEED` >=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThan(Float value) {
            addCriterion("`SPEED` <", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThanOrEqualTo(Float value) {
            addCriterion("`SPEED` <=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedIn(List<Float> values) {
            addCriterion("`SPEED` in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotIn(List<Float> values) {
            addCriterion("`SPEED` not in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedBetween(Float value1, Float value2) {
            addCriterion("`SPEED` between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotBetween(Float value1, Float value2) {
            addCriterion("`SPEED` not between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andTackIsNull() {
            addCriterion("`TACK` is null");
            return (Criteria) this;
        }

        public Criteria andTackIsNotNull() {
            addCriterion("`TACK` is not null");
            return (Criteria) this;
        }

        public Criteria andTackEqualTo(Float value) {
            addCriterion("`TACK` =", value, "tack");
            return (Criteria) this;
        }

        public Criteria andTackNotEqualTo(Float value) {
            addCriterion("`TACK` <>", value, "tack");
            return (Criteria) this;
        }

        public Criteria andTackGreaterThan(Float value) {
            addCriterion("`TACK` >", value, "tack");
            return (Criteria) this;
        }

        public Criteria andTackGreaterThanOrEqualTo(Float value) {
            addCriterion("`TACK` >=", value, "tack");
            return (Criteria) this;
        }

        public Criteria andTackLessThan(Float value) {
            addCriterion("`TACK` <", value, "tack");
            return (Criteria) this;
        }

        public Criteria andTackLessThanOrEqualTo(Float value) {
            addCriterion("`TACK` <=", value, "tack");
            return (Criteria) this;
        }

        public Criteria andTackIn(List<Float> values) {
            addCriterion("`TACK` in", values, "tack");
            return (Criteria) this;
        }

        public Criteria andTackNotIn(List<Float> values) {
            addCriterion("`TACK` not in", values, "tack");
            return (Criteria) this;
        }

        public Criteria andTackBetween(Float value1, Float value2) {
            addCriterion("`TACK` between", value1, value2, "tack");
            return (Criteria) this;
        }

        public Criteria andTackNotBetween(Float value1, Float value2) {
            addCriterion("`TACK` not between", value1, value2, "tack");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthIsNull() {
            addCriterion("`SIGNAL_STRENGTH` is null");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthIsNotNull() {
            addCriterion("`SIGNAL_STRENGTH` is not null");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthEqualTo(Integer value) {
            addCriterion("`SIGNAL_STRENGTH` =", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthNotEqualTo(Integer value) {
            addCriterion("`SIGNAL_STRENGTH` <>", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthGreaterThan(Integer value) {
            addCriterion("`SIGNAL_STRENGTH` >", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SIGNAL_STRENGTH` >=", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthLessThan(Integer value) {
            addCriterion("`SIGNAL_STRENGTH` <", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthLessThanOrEqualTo(Integer value) {
            addCriterion("`SIGNAL_STRENGTH` <=", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthIn(List<Integer> values) {
            addCriterion("`SIGNAL_STRENGTH` in", values, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthNotIn(List<Integer> values) {
            addCriterion("`SIGNAL_STRENGTH` not in", values, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthBetween(Integer value1, Integer value2) {
            addCriterion("`SIGNAL_STRENGTH` between", value1, value2, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthNotBetween(Integer value1, Integer value2) {
            addCriterion("`SIGNAL_STRENGTH` not between", value1, value2, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureIsNull() {
            addCriterion("`CPU_TEMPRETURE` is null");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureIsNotNull() {
            addCriterion("`CPU_TEMPRETURE` is not null");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureEqualTo(Integer value) {
            addCriterion("`CPU_TEMPRETURE` =", value, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureNotEqualTo(Integer value) {
            addCriterion("`CPU_TEMPRETURE` <>", value, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureGreaterThan(Integer value) {
            addCriterion("`CPU_TEMPRETURE` >", value, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureGreaterThanOrEqualTo(Integer value) {
            addCriterion("`CPU_TEMPRETURE` >=", value, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureLessThan(Integer value) {
            addCriterion("`CPU_TEMPRETURE` <", value, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureLessThanOrEqualTo(Integer value) {
            addCriterion("`CPU_TEMPRETURE` <=", value, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureIn(List<Integer> values) {
            addCriterion("`CPU_TEMPRETURE` in", values, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureNotIn(List<Integer> values) {
            addCriterion("`CPU_TEMPRETURE` not in", values, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureBetween(Integer value1, Integer value2) {
            addCriterion("`CPU_TEMPRETURE` between", value1, value2, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andCpuTempretureNotBetween(Integer value1, Integer value2) {
            addCriterion("`CPU_TEMPRETURE` not between", value1, value2, "cpuTempreture");
            return (Criteria) this;
        }

        public Criteria andLibvIsNull() {
            addCriterion("`LIBV` is null");
            return (Criteria) this;
        }

        public Criteria andLibvIsNotNull() {
            addCriterion("`LIBV` is not null");
            return (Criteria) this;
        }

        public Criteria andLibvEqualTo(Float value) {
            addCriterion("`LIBV` =", value, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvNotEqualTo(Float value) {
            addCriterion("`LIBV` <>", value, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvGreaterThan(Float value) {
            addCriterion("`LIBV` >", value, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvGreaterThanOrEqualTo(Float value) {
            addCriterion("`LIBV` >=", value, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvLessThan(Float value) {
            addCriterion("`LIBV` <", value, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvLessThanOrEqualTo(Float value) {
            addCriterion("`LIBV` <=", value, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvIn(List<Float> values) {
            addCriterion("`LIBV` in", values, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvNotIn(List<Float> values) {
            addCriterion("`LIBV` not in", values, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvBetween(Float value1, Float value2) {
            addCriterion("`LIBV` between", value1, value2, "libv");
            return (Criteria) this;
        }

        public Criteria andLibvNotBetween(Float value1, Float value2) {
            addCriterion("`LIBV` not between", value1, value2, "libv");
            return (Criteria) this;
        }

        public Criteria andPvbvIsNull() {
            addCriterion("`PVBV` is null");
            return (Criteria) this;
        }

        public Criteria andPvbvIsNotNull() {
            addCriterion("`PVBV` is not null");
            return (Criteria) this;
        }

        public Criteria andPvbvEqualTo(Float value) {
            addCriterion("`PVBV` =", value, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvNotEqualTo(Float value) {
            addCriterion("`PVBV` <>", value, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvGreaterThan(Float value) {
            addCriterion("`PVBV` >", value, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvGreaterThanOrEqualTo(Float value) {
            addCriterion("`PVBV` >=", value, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvLessThan(Float value) {
            addCriterion("`PVBV` <", value, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvLessThanOrEqualTo(Float value) {
            addCriterion("`PVBV` <=", value, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvIn(List<Float> values) {
            addCriterion("`PVBV` in", values, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvNotIn(List<Float> values) {
            addCriterion("`PVBV` not in", values, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvBetween(Float value1, Float value2) {
            addCriterion("`PVBV` between", value1, value2, "pvbv");
            return (Criteria) this;
        }

        public Criteria andPvbvNotBetween(Float value1, Float value2) {
            addCriterion("`PVBV` not between", value1, value2, "pvbv");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`CREATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`CREATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`CREATE_TIME` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`CREATE_TIME` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`CREATE_TIME` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`CREATE_TIME` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`CREATE_TIME` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`UPDATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`UPDATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`UPDATE_TIME` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`UPDATE_TIME` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("`DEL_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("`DEL_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("`DEL_FLAG` >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("`DEL_FLAG` <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_acq_data
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_acq_data
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}