package com.cetcme.springBootDemo.domain;

import java.io.Serializable;

public class AcqTblIndex implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acqtbl_index.INDEX_ID
     *
     * @mbggenerated
     */
    private Long indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acqtbl_index.DEVICE_NO
     *
     * @mbggenerated
     */
    private String deviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acqtbl_index.SHIP_NO
     *
     * @mbggenerated
     */
    private String shipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acqtbl_index.TABLE_SUFF
     *
     * @mbggenerated
     */
    private String tableSuff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acqtbl_index
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acqtbl_index.INDEX_ID
     *
     * @return the value of t_acqtbl_index.INDEX_ID
     *
     * @mbggenerated
     */
    public Long getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acqtbl_index.INDEX_ID
     *
     * @param indexId the value for t_acqtbl_index.INDEX_ID
     *
     * @mbggenerated
     */
    public void setIndexId(Long indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acqtbl_index.DEVICE_NO
     *
     * @return the value of t_acqtbl_index.DEVICE_NO
     *
     * @mbggenerated
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acqtbl_index.DEVICE_NO
     *
     * @param deviceNo the value for t_acqtbl_index.DEVICE_NO
     *
     * @mbggenerated
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo == null ? null : deviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acqtbl_index.SHIP_NO
     *
     * @return the value of t_acqtbl_index.SHIP_NO
     *
     * @mbggenerated
     */
    public String getShipNo() {
        return shipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acqtbl_index.SHIP_NO
     *
     * @param shipNo the value for t_acqtbl_index.SHIP_NO
     *
     * @mbggenerated
     */
    public void setShipNo(String shipNo) {
        this.shipNo = shipNo == null ? null : shipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acqtbl_index.TABLE_SUFF
     *
     * @return the value of t_acqtbl_index.TABLE_SUFF
     *
     * @mbggenerated
     */
    public String getTableSuff() {
        return tableSuff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acqtbl_index.TABLE_SUFF
     *
     * @param tableSuff the value for t_acqtbl_index.TABLE_SUFF
     *
     * @mbggenerated
     */
    public void setTableSuff(String tableSuff) {
        this.tableSuff = tableSuff == null ? null : tableSuff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acqtbl_index
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", indexId=").append(indexId);
        sb.append(", deviceNo=").append(deviceNo);
        sb.append(", shipNo=").append(shipNo);
        sb.append(", tableSuff=").append(tableSuff);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}