package com.cetcme.springBootDemo.domain;

import java.io.Serializable;

public class Circle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.CIRCLE_ID
     *
     * @mbggenerated
     */
    private Long circleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.FENCE_ID
     *
     * @mbggenerated
     */
    private Long fenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.BMAP_LONGITUDE
     *
     * @mbggenerated
     */
    private Double bmapLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.BMAP_LATITUDE
     *
     * @mbggenerated
     */
    private Double bmapLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.LONGITUDE
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.LATITUDE
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.RADIUS
     *
     * @mbggenerated
     */
    private Double radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.CIRCLE_ID
     *
     * @return the value of t_circle.CIRCLE_ID
     *
     * @mbggenerated
     */
    public Long getCircleId() {
        return circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.CIRCLE_ID
     *
     * @param circleId the value for t_circle.CIRCLE_ID
     *
     * @mbggenerated
     */
    public void setCircleId(Long circleId) {
        this.circleId = circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.FENCE_ID
     *
     * @return the value of t_circle.FENCE_ID
     *
     * @mbggenerated
     */
    public Long getFenceId() {
        return fenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.FENCE_ID
     *
     * @param fenceId the value for t_circle.FENCE_ID
     *
     * @mbggenerated
     */
    public void setFenceId(Long fenceId) {
        this.fenceId = fenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.BMAP_LONGITUDE
     *
     * @return the value of t_circle.BMAP_LONGITUDE
     *
     * @mbggenerated
     */
    public Double getBmapLongitude() {
        return bmapLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.BMAP_LONGITUDE
     *
     * @param bmapLongitude the value for t_circle.BMAP_LONGITUDE
     *
     * @mbggenerated
     */
    public void setBmapLongitude(Double bmapLongitude) {
        this.bmapLongitude = bmapLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.BMAP_LATITUDE
     *
     * @return the value of t_circle.BMAP_LATITUDE
     *
     * @mbggenerated
     */
    public Double getBmapLatitude() {
        return bmapLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.BMAP_LATITUDE
     *
     * @param bmapLatitude the value for t_circle.BMAP_LATITUDE
     *
     * @mbggenerated
     */
    public void setBmapLatitude(Double bmapLatitude) {
        this.bmapLatitude = bmapLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.LONGITUDE
     *
     * @return the value of t_circle.LONGITUDE
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.LONGITUDE
     *
     * @param longitude the value for t_circle.LONGITUDE
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.LATITUDE
     *
     * @return the value of t_circle.LATITUDE
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.LATITUDE
     *
     * @param latitude the value for t_circle.LATITUDE
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.RADIUS
     *
     * @return the value of t_circle.RADIUS
     *
     * @mbggenerated
     */
    public Double getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.RADIUS
     *
     * @param radius the value for t_circle.RADIUS
     *
     * @mbggenerated
     */
    public void setRadius(Double radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", circleId=").append(circleId);
        sb.append(", fenceId=").append(fenceId);
        sb.append(", bmapLongitude=").append(bmapLongitude);
        sb.append(", bmapLatitude=").append(bmapLatitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", radius=").append(radius);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}