package com.cetcme.springBootDemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_device
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_device
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_device
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public DeviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_device
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("`DEVICE_ID` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("`DEVICE_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("`DEVICE_ID` =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("`DEVICE_ID` >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("`DEVICE_ID` <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("`DEVICE_ID` in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("`DEVICE_ID` not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIsNull() {
            addCriterion("`DEVICE_NO` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIsNotNull() {
            addCriterion("`DEVICE_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceNoEqualTo(String value) {
            addCriterion("`DEVICE_NO` =", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotEqualTo(String value) {
            addCriterion("`DEVICE_NO` <>", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoGreaterThan(String value) {
            addCriterion("`DEVICE_NO` >", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
            addCriterion("`DEVICE_NO` >=", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLessThan(String value) {
            addCriterion("`DEVICE_NO` <", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLessThanOrEqualTo(String value) {
            addCriterion("`DEVICE_NO` <=", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLike(String value) {
            addCriterion("`DEVICE_NO` like", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotLike(String value) {
            addCriterion("`DEVICE_NO` not like", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIn(List<String> values) {
            addCriterion("`DEVICE_NO` in", values, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotIn(List<String> values) {
            addCriterion("`DEVICE_NO` not in", values, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoBetween(String value1, String value2) {
            addCriterion("`DEVICE_NO` between", value1, value2, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotBetween(String value1, String value2) {
            addCriterion("`DEVICE_NO` not between", value1, value2, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoIsNull() {
            addCriterion("`IDCARDREADER_NO` is null");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoIsNotNull() {
            addCriterion("`IDCARDREADER_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoEqualTo(String value) {
            addCriterion("`IDCARDREADER_NO` =", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoNotEqualTo(String value) {
            addCriterion("`IDCARDREADER_NO` <>", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoGreaterThan(String value) {
            addCriterion("`IDCARDREADER_NO` >", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoGreaterThanOrEqualTo(String value) {
            addCriterion("`IDCARDREADER_NO` >=", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoLessThan(String value) {
            addCriterion("`IDCARDREADER_NO` <", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoLessThanOrEqualTo(String value) {
            addCriterion("`IDCARDREADER_NO` <=", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoLike(String value) {
            addCriterion("`IDCARDREADER_NO` like", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoNotLike(String value) {
            addCriterion("`IDCARDREADER_NO` not like", value, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoIn(List<String> values) {
            addCriterion("`IDCARDREADER_NO` in", values, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoNotIn(List<String> values) {
            addCriterion("`IDCARDREADER_NO` not in", values, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoBetween(String value1, String value2) {
            addCriterion("`IDCARDREADER_NO` between", value1, value2, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andIdcardreaderNoNotBetween(String value1, String value2) {
            addCriterion("`IDCARDREADER_NO` not between", value1, value2, "idcardreaderNo");
            return (Criteria) this;
        }

        public Criteria andPairFlagIsNull() {
            addCriterion("`PAIR_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andPairFlagIsNotNull() {
            addCriterion("`PAIR_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andPairFlagEqualTo(Boolean value) {
            addCriterion("`PAIR_FLAG` =", value, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagNotEqualTo(Boolean value) {
            addCriterion("`PAIR_FLAG` <>", value, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagGreaterThan(Boolean value) {
            addCriterion("`PAIR_FLAG` >", value, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`PAIR_FLAG` >=", value, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagLessThan(Boolean value) {
            addCriterion("`PAIR_FLAG` <", value, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("`PAIR_FLAG` <=", value, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagIn(List<Boolean> values) {
            addCriterion("`PAIR_FLAG` in", values, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagNotIn(List<Boolean> values) {
            addCriterion("`PAIR_FLAG` not in", values, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("`PAIR_FLAG` between", value1, value2, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andPairFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`PAIR_FLAG` not between", value1, value2, "pairFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagIsNull() {
            addCriterion("`OFFLINE_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagIsNotNull() {
            addCriterion("`OFFLINE_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagEqualTo(Boolean value) {
            addCriterion("`OFFLINE_FLAG` =", value, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagNotEqualTo(Boolean value) {
            addCriterion("`OFFLINE_FLAG` <>", value, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagGreaterThan(Boolean value) {
            addCriterion("`OFFLINE_FLAG` >", value, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`OFFLINE_FLAG` >=", value, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagLessThan(Boolean value) {
            addCriterion("`OFFLINE_FLAG` <", value, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("`OFFLINE_FLAG` <=", value, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagIn(List<Boolean> values) {
            addCriterion("`OFFLINE_FLAG` in", values, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagNotIn(List<Boolean> values) {
            addCriterion("`OFFLINE_FLAG` not in", values, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("`OFFLINE_FLAG` between", value1, value2, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andOfflineFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`OFFLINE_FLAG` not between", value1, value2, "offlineFlag");
            return (Criteria) this;
        }

        public Criteria andFenceIdIsNull() {
            addCriterion("`FENCE_ID` is null");
            return (Criteria) this;
        }

        public Criteria andFenceIdIsNotNull() {
            addCriterion("`FENCE_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andFenceIdEqualTo(Long value) {
            addCriterion("`FENCE_ID` =", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdNotEqualTo(Long value) {
            addCriterion("`FENCE_ID` <>", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdGreaterThan(Long value) {
            addCriterion("`FENCE_ID` >", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`FENCE_ID` >=", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdLessThan(Long value) {
            addCriterion("`FENCE_ID` <", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdLessThanOrEqualTo(Long value) {
            addCriterion("`FENCE_ID` <=", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdIn(List<Long> values) {
            addCriterion("`FENCE_ID` in", values, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdNotIn(List<Long> values) {
            addCriterion("`FENCE_ID` not in", values, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdBetween(Long value1, Long value2) {
            addCriterion("`FENCE_ID` between", value1, value2, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdNotBetween(Long value1, Long value2) {
            addCriterion("`FENCE_ID` not between", value1, value2, "fenceId");
            return (Criteria) this;
        }

        public Criteria andAltitudeIsNull() {
            addCriterion("`ALTITUDE` is null");
            return (Criteria) this;
        }

        public Criteria andAltitudeIsNotNull() {
            addCriterion("`ALTITUDE` is not null");
            return (Criteria) this;
        }

        public Criteria andAltitudeEqualTo(Double value) {
            addCriterion("`ALTITUDE` =", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeNotEqualTo(Double value) {
            addCriterion("`ALTITUDE` <>", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeGreaterThan(Double value) {
            addCriterion("`ALTITUDE` >", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`ALTITUDE` >=", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeLessThan(Double value) {
            addCriterion("`ALTITUDE` <", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeLessThanOrEqualTo(Double value) {
            addCriterion("`ALTITUDE` <=", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeIn(List<Double> values) {
            addCriterion("`ALTITUDE` in", values, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeNotIn(List<Double> values) {
            addCriterion("`ALTITUDE` not in", values, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeBetween(Double value1, Double value2) {
            addCriterion("`ALTITUDE` between", value1, value2, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeNotBetween(Double value1, Double value2) {
            addCriterion("`ALTITUDE` not between", value1, value2, "altitude");
            return (Criteria) this;
        }

        public Criteria andHdopIsNull() {
            addCriterion("`HDOP` is null");
            return (Criteria) this;
        }

        public Criteria andHdopIsNotNull() {
            addCriterion("`HDOP` is not null");
            return (Criteria) this;
        }

        public Criteria andHdopEqualTo(Double value) {
            addCriterion("`HDOP` =", value, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopNotEqualTo(Double value) {
            addCriterion("`HDOP` <>", value, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopGreaterThan(Double value) {
            addCriterion("`HDOP` >", value, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopGreaterThanOrEqualTo(Double value) {
            addCriterion("`HDOP` >=", value, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopLessThan(Double value) {
            addCriterion("`HDOP` <", value, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopLessThanOrEqualTo(Double value) {
            addCriterion("`HDOP` <=", value, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopIn(List<Double> values) {
            addCriterion("`HDOP` in", values, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopNotIn(List<Double> values) {
            addCriterion("`HDOP` not in", values, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopBetween(Double value1, Double value2) {
            addCriterion("`HDOP` between", value1, value2, "hdop");
            return (Criteria) this;
        }

        public Criteria andHdopNotBetween(Double value1, Double value2) {
            addCriterion("`HDOP` not between", value1, value2, "hdop");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntIsNull() {
            addCriterion("`SATELLITE_CNT` is null");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntIsNotNull() {
            addCriterion("`SATELLITE_CNT` is not null");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntEqualTo(Integer value) {
            addCriterion("`SATELLITE_CNT` =", value, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntNotEqualTo(Integer value) {
            addCriterion("`SATELLITE_CNT` <>", value, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntGreaterThan(Integer value) {
            addCriterion("`SATELLITE_CNT` >", value, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SATELLITE_CNT` >=", value, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntLessThan(Integer value) {
            addCriterion("`SATELLITE_CNT` <", value, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntLessThanOrEqualTo(Integer value) {
            addCriterion("`SATELLITE_CNT` <=", value, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntIn(List<Integer> values) {
            addCriterion("`SATELLITE_CNT` in", values, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntNotIn(List<Integer> values) {
            addCriterion("`SATELLITE_CNT` not in", values, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntBetween(Integer value1, Integer value2) {
            addCriterion("`SATELLITE_CNT` between", value1, value2, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSatelliteCntNotBetween(Integer value1, Integer value2) {
            addCriterion("`SATELLITE_CNT` not between", value1, value2, "satelliteCnt");
            return (Criteria) this;
        }

        public Criteria andSkewXIsNull() {
            addCriterion("`SKEW_X` is null");
            return (Criteria) this;
        }

        public Criteria andSkewXIsNotNull() {
            addCriterion("`SKEW_X` is not null");
            return (Criteria) this;
        }

        public Criteria andSkewXEqualTo(Integer value) {
            addCriterion("`SKEW_X` =", value, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXNotEqualTo(Integer value) {
            addCriterion("`SKEW_X` <>", value, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXGreaterThan(Integer value) {
            addCriterion("`SKEW_X` >", value, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SKEW_X` >=", value, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXLessThan(Integer value) {
            addCriterion("`SKEW_X` <", value, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXLessThanOrEqualTo(Integer value) {
            addCriterion("`SKEW_X` <=", value, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXIn(List<Integer> values) {
            addCriterion("`SKEW_X` in", values, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXNotIn(List<Integer> values) {
            addCriterion("`SKEW_X` not in", values, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXBetween(Integer value1, Integer value2) {
            addCriterion("`SKEW_X` between", value1, value2, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewXNotBetween(Integer value1, Integer value2) {
            addCriterion("`SKEW_X` not between", value1, value2, "skewX");
            return (Criteria) this;
        }

        public Criteria andSkewYIsNull() {
            addCriterion("`SKEW_Y` is null");
            return (Criteria) this;
        }

        public Criteria andSkewYIsNotNull() {
            addCriterion("`SKEW_Y` is not null");
            return (Criteria) this;
        }

        public Criteria andSkewYEqualTo(Integer value) {
            addCriterion("`SKEW_Y` =", value, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYNotEqualTo(Integer value) {
            addCriterion("`SKEW_Y` <>", value, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYGreaterThan(Integer value) {
            addCriterion("`SKEW_Y` >", value, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SKEW_Y` >=", value, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYLessThan(Integer value) {
            addCriterion("`SKEW_Y` <", value, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYLessThanOrEqualTo(Integer value) {
            addCriterion("`SKEW_Y` <=", value, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYIn(List<Integer> values) {
            addCriterion("`SKEW_Y` in", values, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYNotIn(List<Integer> values) {
            addCriterion("`SKEW_Y` not in", values, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYBetween(Integer value1, Integer value2) {
            addCriterion("`SKEW_Y` between", value1, value2, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewYNotBetween(Integer value1, Integer value2) {
            addCriterion("`SKEW_Y` not between", value1, value2, "skewY");
            return (Criteria) this;
        }

        public Criteria andSkewZIsNull() {
            addCriterion("`SKEW_Z` is null");
            return (Criteria) this;
        }

        public Criteria andSkewZIsNotNull() {
            addCriterion("`SKEW_Z` is not null");
            return (Criteria) this;
        }

        public Criteria andSkewZEqualTo(Integer value) {
            addCriterion("`SKEW_Z` =", value, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZNotEqualTo(Integer value) {
            addCriterion("`SKEW_Z` <>", value, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZGreaterThan(Integer value) {
            addCriterion("`SKEW_Z` >", value, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SKEW_Z` >=", value, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZLessThan(Integer value) {
            addCriterion("`SKEW_Z` <", value, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZLessThanOrEqualTo(Integer value) {
            addCriterion("`SKEW_Z` <=", value, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZIn(List<Integer> values) {
            addCriterion("`SKEW_Z` in", values, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZNotIn(List<Integer> values) {
            addCriterion("`SKEW_Z` not in", values, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZBetween(Integer value1, Integer value2) {
            addCriterion("`SKEW_Z` between", value1, value2, "skewZ");
            return (Criteria) this;
        }

        public Criteria andSkewZNotBetween(Integer value1, Integer value2) {
            addCriterion("`SKEW_Z` not between", value1, value2, "skewZ");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqIsNull() {
            addCriterion("`TRANSMIT_FREQ` is null");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqIsNotNull() {
            addCriterion("`TRANSMIT_FREQ` is not null");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqEqualTo(Integer value) {
            addCriterion("`TRANSMIT_FREQ` =", value, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqNotEqualTo(Integer value) {
            addCriterion("`TRANSMIT_FREQ` <>", value, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqGreaterThan(Integer value) {
            addCriterion("`TRANSMIT_FREQ` >", value, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqGreaterThanOrEqualTo(Integer value) {
            addCriterion("`TRANSMIT_FREQ` >=", value, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqLessThan(Integer value) {
            addCriterion("`TRANSMIT_FREQ` <", value, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqLessThanOrEqualTo(Integer value) {
            addCriterion("`TRANSMIT_FREQ` <=", value, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqIn(List<Integer> values) {
            addCriterion("`TRANSMIT_FREQ` in", values, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqNotIn(List<Integer> values) {
            addCriterion("`TRANSMIT_FREQ` not in", values, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqBetween(Integer value1, Integer value2) {
            addCriterion("`TRANSMIT_FREQ` between", value1, value2, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitFreqNotBetween(Integer value1, Integer value2) {
            addCriterion("`TRANSMIT_FREQ` not between", value1, value2, "transmitFreq");
            return (Criteria) this;
        }

        public Criteria andTransmitDistIsNull() {
            addCriterion("`TRANSMIT_DIST` is null");
            return (Criteria) this;
        }

        public Criteria andTransmitDistIsNotNull() {
            addCriterion("`TRANSMIT_DIST` is not null");
            return (Criteria) this;
        }

        public Criteria andTransmitDistEqualTo(Integer value) {
            addCriterion("`TRANSMIT_DIST` =", value, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistNotEqualTo(Integer value) {
            addCriterion("`TRANSMIT_DIST` <>", value, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistGreaterThan(Integer value) {
            addCriterion("`TRANSMIT_DIST` >", value, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistGreaterThanOrEqualTo(Integer value) {
            addCriterion("`TRANSMIT_DIST` >=", value, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistLessThan(Integer value) {
            addCriterion("`TRANSMIT_DIST` <", value, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistLessThanOrEqualTo(Integer value) {
            addCriterion("`TRANSMIT_DIST` <=", value, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistIn(List<Integer> values) {
            addCriterion("`TRANSMIT_DIST` in", values, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistNotIn(List<Integer> values) {
            addCriterion("`TRANSMIT_DIST` not in", values, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistBetween(Integer value1, Integer value2) {
            addCriterion("`TRANSMIT_DIST` between", value1, value2, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andTransmitDistNotBetween(Integer value1, Integer value2) {
            addCriterion("`TRANSMIT_DIST` not between", value1, value2, "transmitDist");
            return (Criteria) this;
        }

        public Criteria andRecordFreqIsNull() {
            addCriterion("`RECORD_FREQ` is null");
            return (Criteria) this;
        }

        public Criteria andRecordFreqIsNotNull() {
            addCriterion("`RECORD_FREQ` is not null");
            return (Criteria) this;
        }

        public Criteria andRecordFreqEqualTo(Integer value) {
            addCriterion("`RECORD_FREQ` =", value, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqNotEqualTo(Integer value) {
            addCriterion("`RECORD_FREQ` <>", value, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqGreaterThan(Integer value) {
            addCriterion("`RECORD_FREQ` >", value, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqGreaterThanOrEqualTo(Integer value) {
            addCriterion("`RECORD_FREQ` >=", value, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqLessThan(Integer value) {
            addCriterion("`RECORD_FREQ` <", value, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqLessThanOrEqualTo(Integer value) {
            addCriterion("`RECORD_FREQ` <=", value, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqIn(List<Integer> values) {
            addCriterion("`RECORD_FREQ` in", values, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqNotIn(List<Integer> values) {
            addCriterion("`RECORD_FREQ` not in", values, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqBetween(Integer value1, Integer value2) {
            addCriterion("`RECORD_FREQ` between", value1, value2, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordFreqNotBetween(Integer value1, Integer value2) {
            addCriterion("`RECORD_FREQ` not between", value1, value2, "recordFreq");
            return (Criteria) this;
        }

        public Criteria andRecordDistIsNull() {
            addCriterion("`RECORD_DIST` is null");
            return (Criteria) this;
        }

        public Criteria andRecordDistIsNotNull() {
            addCriterion("`RECORD_DIST` is not null");
            return (Criteria) this;
        }

        public Criteria andRecordDistEqualTo(Integer value) {
            addCriterion("`RECORD_DIST` =", value, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistNotEqualTo(Integer value) {
            addCriterion("`RECORD_DIST` <>", value, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistGreaterThan(Integer value) {
            addCriterion("`RECORD_DIST` >", value, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistGreaterThanOrEqualTo(Integer value) {
            addCriterion("`RECORD_DIST` >=", value, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistLessThan(Integer value) {
            addCriterion("`RECORD_DIST` <", value, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistLessThanOrEqualTo(Integer value) {
            addCriterion("`RECORD_DIST` <=", value, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistIn(List<Integer> values) {
            addCriterion("`RECORD_DIST` in", values, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistNotIn(List<Integer> values) {
            addCriterion("`RECORD_DIST` not in", values, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistBetween(Integer value1, Integer value2) {
            addCriterion("`RECORD_DIST` between", value1, value2, "recordDist");
            return (Criteria) this;
        }

        public Criteria andRecordDistNotBetween(Integer value1, Integer value2) {
            addCriterion("`RECORD_DIST` not between", value1, value2, "recordDist");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("`CREATE_USER_ID` is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("`CREATE_USER_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("`CREATE_USER_ID` >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("`CREATE_USER_ID` <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("`CREATE_USER_ID` in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("`CREATE_USER_ID` not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("`CREATE_USER_ID` between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("`CREATE_USER_ID` not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`CREATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`CREATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`CREATE_TIME` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`CREATE_TIME` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`CREATE_TIME` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`CREATE_TIME` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`CREATE_TIME` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("`UPDATE_USER_ID` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("`UPDATE_USER_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Long value) {
            addCriterion("`UPDATE_USER_ID` >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Long value) {
            addCriterion("`UPDATE_USER_ID` <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Long> values) {
            addCriterion("`UPDATE_USER_ID` in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Long> values) {
            addCriterion("`UPDATE_USER_ID` not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("`UPDATE_USER_ID` between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("`UPDATE_USER_ID` not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`UPDATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`UPDATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`UPDATE_TIME` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`UPDATE_TIME` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("`DEL_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("`DEL_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("`DEL_FLAG` >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("`DEL_FLAG` <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_device
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_device
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}