package com.cetcme.springBootDemo.domain;

import java.io.Serializable;
import java.util.Date;

public class Fence implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_ID
     *
     * @mbggenerated
     */
    private Long fenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_NO
     *
     * @mbggenerated
     */
    private String fenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_NAME
     *
     * @mbggenerated
     */
    private String fenceName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_PHONE
     *
     * @mbggenerated
     */
    private String fencePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_LEVEL
     *
     * @mbggenerated
     */
    private String fenceLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.COUNTRY
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_ADDR
     *
     * @mbggenerated
     */
    private String fenceAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.FENCE_TYPE
     *
     * @mbggenerated
     */
    private Integer fenceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.BERTH_AMOUNT
     *
     * @mbggenerated
     */
    private String berthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.DATA_SOURCE
     *
     * @mbggenerated
     */
    private Integer dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fence.DEL_FLAG
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fence
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_ID
     *
     * @return the value of t_fence.FENCE_ID
     *
     * @mbggenerated
     */
    public Long getFenceId() {
        return fenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_ID
     *
     * @param fenceId the value for t_fence.FENCE_ID
     *
     * @mbggenerated
     */
    public void setFenceId(Long fenceId) {
        this.fenceId = fenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_NO
     *
     * @return the value of t_fence.FENCE_NO
     *
     * @mbggenerated
     */
    public String getFenceNo() {
        return fenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_NO
     *
     * @param fenceNo the value for t_fence.FENCE_NO
     *
     * @mbggenerated
     */
    public void setFenceNo(String fenceNo) {
        this.fenceNo = fenceNo == null ? null : fenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_NAME
     *
     * @return the value of t_fence.FENCE_NAME
     *
     * @mbggenerated
     */
    public String getFenceName() {
        return fenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_PHONE
     *
     * @param fenceName the value for t_fence.FENCE_PHONE
     *
     * @mbggenerated
     */
    public void setFencePhone(String fencePhone) {
        this.fencePhone = fencePhone == null ? null : fencePhone.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_PHONE
     *
     * @return the value of t_fence.FENCE_PHONE
     *
     * @mbggenerated
     */
    public String getFencePhone() {
        return fencePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_NAME
     *
     * @param fenceName the value for t_fence.FENCE_NAME
     *
     * @mbggenerated
     */
    public void setFenceName(String fenceName) {
        this.fenceName = fenceName == null ? null : fenceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_LEVEL
     *
     * @return the value of t_fence.FENCE_LEVEL
     *
     * @mbggenerated
     */
    public String getFenceLevel() {
        return fenceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_LEVEL
     *
     * @param fenceLevel the value for t_fence.FENCE_LEVEL
     *
     * @mbggenerated
     */
    public void setFenceLevel(String fenceLevel) {
        this.fenceLevel = fenceLevel == null ? null : fenceLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.CITY
     *
     * @return the value of t_fence.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.CITY
     *
     * @param city the value for t_fence.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.COUNTRY
     *
     * @return the value of t_fence.COUNTRY
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.COUNTRY
     *
     * @param country the value for t_fence.COUNTRY
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_ADDR
     *
     * @return the value of t_fence.FENCE_ADDR
     *
     * @mbggenerated
     */
    public String getFenceAddr() {
        return fenceAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_ADDR
     *
     * @param fenceAddr the value for t_fence.FENCE_ADDR
     *
     * @mbggenerated
     */
    public void setFenceAddr(String fenceAddr) {
        this.fenceAddr = fenceAddr == null ? null : fenceAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.FENCE_TYPE
     *
     * @return the value of t_fence.FENCE_TYPE
     *
     * @mbggenerated
     */
    public Integer getFenceType() {
        return fenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.FENCE_TYPE
     *
     * @param fenceType the value for t_fence.FENCE_TYPE
     *
     * @mbggenerated
     */
    public void setFenceType(Integer fenceType) {
        this.fenceType = fenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.BERTH_AMOUNT
     *
     * @return the value of t_fence.BERTH_AMOUNT
     *
     * @mbggenerated
     */
    public String getBerthAmount() {
        return berthAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.BERTH_AMOUNT
     *
     * @param berthAmount the value for t_fence.BERTH_AMOUNT
     *
     * @mbggenerated
     */
    public void setBerthAmount(String berthAmount) {
        this.berthAmount = berthAmount == null ? null : berthAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.CREATE_USER_ID
     *
     * @return the value of t_fence.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.CREATE_USER_ID
     *
     * @param createUserId the value for t_fence.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.CREATE_TIME
     *
     * @return the value of t_fence.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.CREATE_TIME
     *
     * @param createTime the value for t_fence.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.UPDATE_USER_ID
     *
     * @return the value of t_fence.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.UPDATE_USER_ID
     *
     * @param updateUserId the value for t_fence.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.UPDATE_TIME
     *
     * @return the value of t_fence.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.UPDATE_TIME
     *
     * @param updateTime the value for t_fence.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.DATA_SOURCE
     *
     * @return the value of t_fence.DATA_SOURCE
     *
     * @mbggenerated
     */
    public Integer getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.DATA_SOURCE
     *
     * @param dataSource the value for t_fence.DATA_SOURCE
     *
     * @mbggenerated
     */
    public void setDataSource(Integer dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fence.DEL_FLAG
     *
     * @return the value of t_fence.DEL_FLAG
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fence.DEL_FLAG
     *
     * @param delFlag the value for t_fence.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fence
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fenceId=").append(fenceId);
        sb.append(", fenceNo=").append(fenceNo);
        sb.append(", fenceName=").append(fenceName);
        sb.append(", fencePhone=").append(fencePhone);
        sb.append(", fenceLevel=").append(fenceLevel);
        sb.append(", city=").append(city);
        sb.append(", country=").append(country);
        sb.append(", fenceAddr=").append(fenceAddr);
        sb.append(", fenceType=").append(fenceType);
        sb.append(", berthAmount=").append(berthAmount);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", dataSource=").append(dataSource);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}