package com.cetcme.springBootDemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IofLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public IofLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIofLogIdIsNull() {
            addCriterion("`IOF_LOG_ID` is null");
            return (Criteria) this;
        }

        public Criteria andIofLogIdIsNotNull() {
            addCriterion("`IOF_LOG_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andIofLogIdEqualTo(Long value) {
            addCriterion("`IOF_LOG_ID` =", value, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdNotEqualTo(Long value) {
            addCriterion("`IOF_LOG_ID` <>", value, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdGreaterThan(Long value) {
            addCriterion("`IOF_LOG_ID` >", value, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`IOF_LOG_ID` >=", value, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdLessThan(Long value) {
            addCriterion("`IOF_LOG_ID` <", value, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdLessThanOrEqualTo(Long value) {
            addCriterion("`IOF_LOG_ID` <=", value, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdIn(List<Long> values) {
            addCriterion("`IOF_LOG_ID` in", values, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdNotIn(List<Long> values) {
            addCriterion("`IOF_LOG_ID` not in", values, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdBetween(Long value1, Long value2) {
            addCriterion("`IOF_LOG_ID` between", value1, value2, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofLogIdNotBetween(Long value1, Long value2) {
            addCriterion("`IOF_LOG_ID` not between", value1, value2, "iofLogId");
            return (Criteria) this;
        }

        public Criteria andIofFlagIsNull() {
            addCriterion("`IOF_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andIofFlagIsNotNull() {
            addCriterion("`IOF_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andIofFlagEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` =", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagNotEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` <>", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagGreaterThan(Integer value) {
            addCriterion("`IOF_FLAG` >", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` >=", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagLessThan(Integer value) {
            addCriterion("`IOF_FLAG` <", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagLessThanOrEqualTo(Integer value) {
            addCriterion("`IOF_FLAG` <=", value, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagIn(List<Integer> values) {
            addCriterion("`IOF_FLAG` in", values, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagNotIn(List<Integer> values) {
            addCriterion("`IOF_FLAG` not in", values, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagBetween(Integer value1, Integer value2) {
            addCriterion("`IOF_FLAG` between", value1, value2, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andIofFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("`IOF_FLAG` not between", value1, value2, "iofFlag");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("`DEVICE_ID` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("`DEVICE_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("`DEVICE_ID` =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("`DEVICE_ID` >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("`DEVICE_ID` <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("`DEVICE_ID` in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("`DEVICE_ID` not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIsNull() {
            addCriterion("`DEVICE_NO` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIsNotNull() {
            addCriterion("`DEVICE_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceNoEqualTo(String value) {
            addCriterion("`DEVICE_NO` =", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotEqualTo(String value) {
            addCriterion("`DEVICE_NO` <>", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoGreaterThan(String value) {
            addCriterion("`DEVICE_NO` >", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
            addCriterion("`DEVICE_NO` >=", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLessThan(String value) {
            addCriterion("`DEVICE_NO` <", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLessThanOrEqualTo(String value) {
            addCriterion("`DEVICE_NO` <=", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoLike(String value) {
            addCriterion("`DEVICE_NO` like", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotLike(String value) {
            addCriterion("`DEVICE_NO` not like", value, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoIn(List<String> values) {
            addCriterion("`DEVICE_NO` in", values, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotIn(List<String> values) {
            addCriterion("`DEVICE_NO` not in", values, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoBetween(String value1, String value2) {
            addCriterion("`DEVICE_NO` between", value1, value2, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andDeviceNoNotBetween(String value1, String value2) {
            addCriterion("`DEVICE_NO` not between", value1, value2, "deviceNo");
            return (Criteria) this;
        }

        public Criteria andShipIdIsNull() {
            addCriterion("`SHIP_ID` is null");
            return (Criteria) this;
        }

        public Criteria andShipIdIsNotNull() {
            addCriterion("`SHIP_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andShipIdEqualTo(Long value) {
            addCriterion("`SHIP_ID` =", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotEqualTo(Long value) {
            addCriterion("`SHIP_ID` <>", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdGreaterThan(Long value) {
            addCriterion("`SHIP_ID` >", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`SHIP_ID` >=", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdLessThan(Long value) {
            addCriterion("`SHIP_ID` <", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdLessThanOrEqualTo(Long value) {
            addCriterion("`SHIP_ID` <=", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdIn(List<Long> values) {
            addCriterion("`SHIP_ID` in", values, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotIn(List<Long> values) {
            addCriterion("`SHIP_ID` not in", values, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdBetween(Long value1, Long value2) {
            addCriterion("`SHIP_ID` between", value1, value2, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotBetween(Long value1, Long value2) {
            addCriterion("`SHIP_ID` not between", value1, value2, "shipId");
            return (Criteria) this;
        }

        public Criteria andFenceIdIsNull() {
            addCriterion("`FENCE_ID` is null");
            return (Criteria) this;
        }

        public Criteria andFenceIdIsNotNull() {
            addCriterion("`FENCE_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andFenceIdEqualTo(Long value) {
            addCriterion("`FENCE_ID` =", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdNotEqualTo(Long value) {
            addCriterion("`FENCE_ID` <>", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdGreaterThan(Long value) {
            addCriterion("`FENCE_ID` >", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`FENCE_ID` >=", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdLessThan(Long value) {
            addCriterion("`FENCE_ID` <", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdLessThanOrEqualTo(Long value) {
            addCriterion("`FENCE_ID` <=", value, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdIn(List<Long> values) {
            addCriterion("`FENCE_ID` in", values, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdNotIn(List<Long> values) {
            addCriterion("`FENCE_ID` not in", values, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdBetween(Long value1, Long value2) {
            addCriterion("`FENCE_ID` between", value1, value2, "fenceId");
            return (Criteria) this;
        }

        public Criteria andFenceIdNotBetween(Long value1, Long value2) {
            addCriterion("`FENCE_ID` not between", value1, value2, "fenceId");
            return (Criteria) this;
        }

        public Criteria andIofTimeIsNull() {
            addCriterion("`IOF_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andIofTimeIsNotNull() {
            addCriterion("`IOF_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andIofTimeEqualTo(Date value) {
            addCriterion("`IOF_TIME` =", value, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeNotEqualTo(Date value) {
            addCriterion("`IOF_TIME` <>", value, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeGreaterThan(Date value) {
            addCriterion("`IOF_TIME` >", value, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`IOF_TIME` >=", value, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeLessThan(Date value) {
            addCriterion("`IOF_TIME` <", value, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeLessThanOrEqualTo(Date value) {
            addCriterion("`IOF_TIME` <=", value, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeIn(List<Date> values) {
            addCriterion("`IOF_TIME` in", values, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeNotIn(List<Date> values) {
            addCriterion("`IOF_TIME` not in", values, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeBetween(Date value1, Date value2) {
            addCriterion("`IOF_TIME` between", value1, value2, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofTimeNotBetween(Date value1, Date value2) {
            addCriterion("`IOF_TIME` not between", value1, value2, "iofTime");
            return (Criteria) this;
        }

        public Criteria andIofStatusIsNull() {
            addCriterion("`IOF_STATUS` is null");
            return (Criteria) this;
        }

        public Criteria andIofStatusIsNotNull() {
            addCriterion("`IOF_STATUS` is not null");
            return (Criteria) this;
        }

        public Criteria andIofStatusEqualTo(Integer value) {
            addCriterion("`IOF_STATUS` =", value, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusNotEqualTo(Integer value) {
            addCriterion("`IOF_STATUS` <>", value, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusGreaterThan(Integer value) {
            addCriterion("`IOF_STATUS` >", value, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`IOF_STATUS` >=", value, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusLessThan(Integer value) {
            addCriterion("`IOF_STATUS` <", value, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`IOF_STATUS` <=", value, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusIn(List<Integer> values) {
            addCriterion("`IOF_STATUS` in", values, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusNotIn(List<Integer> values) {
            addCriterion("`IOF_STATUS` not in", values, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusBetween(Integer value1, Integer value2) {
            addCriterion("`IOF_STATUS` between", value1, value2, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andIofStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`IOF_STATUS` not between", value1, value2, "iofStatus");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("`LONGITUDE` is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("`LONGITUDE` is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("`LONGITUDE` =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("`LONGITUDE` <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("`LONGITUDE` >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`LONGITUDE` >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("`LONGITUDE` <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("`LONGITUDE` <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("`LONGITUDE` in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("`LONGITUDE` not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("`LONGITUDE` between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("`LONGITUDE` not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("`LATITUDE` is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("`LATITUDE` is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("`LATITUDE` =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("`LATITUDE` <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("`LATITUDE` >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`LATITUDE` >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("`LATITUDE` <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("`LATITUDE` <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("`LATITUDE` in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("`LATITUDE` not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("`LATITUDE` between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("`LATITUDE` not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`CREATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`CREATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`CREATE_TIME` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`CREATE_TIME` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`CREATE_TIME` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`CREATE_TIME` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`CREATE_TIME` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`UPDATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`UPDATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`UPDATE_TIME` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`UPDATE_TIME` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("`DEL_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("`DEL_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("`DEL_FLAG` >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("`DEL_FLAG` <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_iof_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}