package com.cetcme.springBootDemo.domain;

import java.io.Serializable;
import java.util.Date;

public class IofLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.IOF_LOG_ID
     *
     * @mbggenerated
     */
    private Long iofLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.IOF_FLAG
     *
     * @mbggenerated
     */
    private Integer iofFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.DEVICE_ID
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.DEVICE_NO
     *
     * @mbggenerated
     */
    private String deviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.SHIP_ID
     *
     * @mbggenerated
     */
    private Long shipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.FENCE_ID
     *
     * @mbggenerated
     */
    private Long fenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.IOF_TIME
     *
     * @mbggenerated
     */
    private Date iofTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.IOF_STATUS
     *
     * @mbggenerated
     */
    private Integer iofStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.LONGITUDE
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.LATITUDE
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_log.DEL_FLAG
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.IOF_LOG_ID
     *
     * @return the value of t_iof_log.IOF_LOG_ID
     *
     * @mbggenerated
     */
    public Long getIofLogId() {
        return iofLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.IOF_LOG_ID
     *
     * @param iofLogId the value for t_iof_log.IOF_LOG_ID
     *
     * @mbggenerated
     */
    public void setIofLogId(Long iofLogId) {
        this.iofLogId = iofLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.IOF_FLAG
     *
     * @return the value of t_iof_log.IOF_FLAG
     *
     * @mbggenerated
     */
    public Integer getIofFlag() {
        return iofFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.IOF_FLAG
     *
     * @param iofFlag the value for t_iof_log.IOF_FLAG
     *
     * @mbggenerated
     */
    public void setIofFlag(Integer iofFlag) {
        this.iofFlag = iofFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.DEVICE_ID
     *
     * @return the value of t_iof_log.DEVICE_ID
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.DEVICE_ID
     *
     * @param deviceId the value for t_iof_log.DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.DEVICE_NO
     *
     * @return the value of t_iof_log.DEVICE_NO
     *
     * @mbggenerated
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.DEVICE_NO
     *
     * @param deviceNo the value for t_iof_log.DEVICE_NO
     *
     * @mbggenerated
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo == null ? null : deviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.SHIP_ID
     *
     * @return the value of t_iof_log.SHIP_ID
     *
     * @mbggenerated
     */
    public Long getShipId() {
        return shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.SHIP_ID
     *
     * @param shipId the value for t_iof_log.SHIP_ID
     *
     * @mbggenerated
     */
    public void setShipId(Long shipId) {
        this.shipId = shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.FENCE_ID
     *
     * @return the value of t_iof_log.FENCE_ID
     *
     * @mbggenerated
     */
    public Long getFenceId() {
        return fenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.FENCE_ID
     *
     * @param fenceId the value for t_iof_log.FENCE_ID
     *
     * @mbggenerated
     */
    public void setFenceId(Long fenceId) {
        this.fenceId = fenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.IOF_TIME
     *
     * @return the value of t_iof_log.IOF_TIME
     *
     * @mbggenerated
     */
    public Date getIofTime() {
        return iofTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.IOF_TIME
     *
     * @param iofTime the value for t_iof_log.IOF_TIME
     *
     * @mbggenerated
     */
    public void setIofTime(Date iofTime) {
        this.iofTime = iofTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.IOF_STATUS
     *
     * @return the value of t_iof_log.IOF_STATUS
     *
     * @mbggenerated
     */
    public Integer getIofStatus() {
        return iofStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.IOF_STATUS
     *
     * @param iofStatus the value for t_iof_log.IOF_STATUS
     *
     * @mbggenerated
     */
    public void setIofStatus(Integer iofStatus) {
        this.iofStatus = iofStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.LONGITUDE
     *
     * @return the value of t_iof_log.LONGITUDE
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.LONGITUDE
     *
     * @param longitude the value for t_iof_log.LONGITUDE
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.LATITUDE
     *
     * @return the value of t_iof_log.LATITUDE
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.LATITUDE
     *
     * @param latitude the value for t_iof_log.LATITUDE
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.CREATE_TIME
     *
     * @return the value of t_iof_log.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.CREATE_TIME
     *
     * @param createTime the value for t_iof_log.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.UPDATE_TIME
     *
     * @return the value of t_iof_log.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.UPDATE_TIME
     *
     * @param updateTime the value for t_iof_log.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_log.DEL_FLAG
     *
     * @return the value of t_iof_log.DEL_FLAG
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_log.DEL_FLAG
     *
     * @param delFlag the value for t_iof_log.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", iofLogId=").append(iofLogId);
        sb.append(", iofFlag=").append(iofFlag);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceNo=").append(deviceNo);
        sb.append(", shipId=").append(shipId);
        sb.append(", fenceId=").append(fenceId);
        sb.append(", iofTime=").append(iofTime);
        sb.append(", iofStatus=").append(iofStatus);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}