package com.cetcme.springBootDemo.domain;

import java.io.Serializable;
import java.util.Date;

public class IofSailor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.IOF_SAILOR_ID
     *
     * @mbggenerated
     */
    private Long iofSailorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.IOF_LOG_ID
     *
     * @mbggenerated
     */
    private Long iofLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.IOF_FLAG
     *
     * @mbggenerated
     */
    private Integer iofFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.DEVICE_ID
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.DEVICE_NO
     *
     * @mbggenerated
     */
    private String deviceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.SHIP_ID
     *
     * @mbggenerated
     */
    private Long shipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.SAILOR_ID_NO
     *
     * @mbggenerated
     */
    private String sailorIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.SAILOR_NAME
     *
     * @mbggenerated
     */
    private String sailorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.PUNCH_TIME
     *
     * @mbggenerated
     */
    private Date punchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.DATA_TYPE
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.IOF_TIME
     *
     * @mbggenerated
     */
    private Date iofTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_iof_sailor.DEL_FLAG
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_iof_sailor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.IOF_SAILOR_ID
     *
     * @return the value of t_iof_sailor.IOF_SAILOR_ID
     *
     * @mbggenerated
     */
    public Long getIofSailorId() {
        return iofSailorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.IOF_SAILOR_ID
     *
     * @param iofSailorId the value for t_iof_sailor.IOF_SAILOR_ID
     *
     * @mbggenerated
     */
    public void setIofSailorId(Long iofSailorId) {
        this.iofSailorId = iofSailorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.IOF_LOG_ID
     *
     * @return the value of t_iof_sailor.IOF_LOG_ID
     *
     * @mbggenerated
     */
    public Long getIofLogId() {
        return iofLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.IOF_LOG_ID
     *
     * @param iofLogId the value for t_iof_sailor.IOF_LOG_ID
     *
     * @mbggenerated
     */
    public void setIofLogId(Long iofLogId) {
        this.iofLogId = iofLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.IOF_FLAG
     *
     * @return the value of t_iof_sailor.IOF_FLAG
     *
     * @mbggenerated
     */
    public Integer getIofFlag() {
        return iofFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.IOF_FLAG
     *
     * @param iofFlag the value for t_iof_sailor.IOF_FLAG
     *
     * @mbggenerated
     */
    public void setIofFlag(Integer iofFlag) {
        this.iofFlag = iofFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.DEVICE_ID
     *
     * @return the value of t_iof_sailor.DEVICE_ID
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.DEVICE_ID
     *
     * @param deviceId the value for t_iof_sailor.DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.DEVICE_NO
     *
     * @return the value of t_iof_sailor.DEVICE_NO
     *
     * @mbggenerated
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.DEVICE_NO
     *
     * @param deviceNo the value for t_iof_sailor.DEVICE_NO
     *
     * @mbggenerated
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo == null ? null : deviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.SHIP_ID
     *
     * @return the value of t_iof_sailor.SHIP_ID
     *
     * @mbggenerated
     */
    public Long getShipId() {
        return shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.SHIP_ID
     *
     * @param shipId the value for t_iof_sailor.SHIP_ID
     *
     * @mbggenerated
     */
    public void setShipId(Long shipId) {
        this.shipId = shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.SAILOR_ID_NO
     *
     * @return the value of t_iof_sailor.SAILOR_ID_NO
     *
     * @mbggenerated
     */
    public String getSailorIdNo() {
        return sailorIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.SAILOR_ID_NO
     *
     * @param sailorIdNo the value for t_iof_sailor.SAILOR_ID_NO
     *
     * @mbggenerated
     */
    public void setSailorIdNo(String sailorIdNo) {
        this.sailorIdNo = sailorIdNo == null ? null : sailorIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.SAILOR_NAME
     *
     * @return the value of t_iof_sailor.SAILOR_NAME
     *
     * @mbggenerated
     */
    public String getSailorName() {
        return sailorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.SAILOR_NAME
     *
     * @param sailorName the value for t_iof_sailor.SAILOR_NAME
     *
     * @mbggenerated
     */
    public void setSailorName(String sailorName) {
        this.sailorName = sailorName == null ? null : sailorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.PUNCH_TIME
     *
     * @return the value of t_iof_sailor.PUNCH_TIME
     *
     * @mbggenerated
     */
    public Date getPunchTime() {
        return punchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.PUNCH_TIME
     *
     * @param punchTime the value for t_iof_sailor.PUNCH_TIME
     *
     * @mbggenerated
     */
    public void setPunchTime(Date punchTime) {
        this.punchTime = punchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.DATA_TYPE
     *
     * @return the value of t_iof_sailor.DATA_TYPE
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.DATA_TYPE
     *
     * @param dataType the value for t_iof_sailor.DATA_TYPE
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.REASON
     *
     * @return the value of t_iof_sailor.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.REASON
     *
     * @param reason the value for t_iof_sailor.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.IOF_TIME
     *
     * @return the value of t_iof_sailor.IOF_TIME
     *
     * @mbggenerated
     */
    public Date getIofTime() {
        return iofTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.IOF_TIME
     *
     * @param iofTime the value for t_iof_sailor.IOF_TIME
     *
     * @mbggenerated
     */
    public void setIofTime(Date iofTime) {
        this.iofTime = iofTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.CREATE_TIME
     *
     * @return the value of t_iof_sailor.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.CREATE_TIME
     *
     * @param createTime the value for t_iof_sailor.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.UPDATE_TIME
     *
     * @return the value of t_iof_sailor.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.UPDATE_TIME
     *
     * @param updateTime the value for t_iof_sailor.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_iof_sailor.DEL_FLAG
     *
     * @return the value of t_iof_sailor.DEL_FLAG
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_iof_sailor.DEL_FLAG
     *
     * @param delFlag the value for t_iof_sailor.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_iof_sailor
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", iofSailorId=").append(iofSailorId);
        sb.append(", iofLogId=").append(iofLogId);
        sb.append(", iofFlag=").append(iofFlag);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceNo=").append(deviceNo);
        sb.append(", shipId=").append(shipId);
        sb.append(", sailorIdNo=").append(sailorIdNo);
        sb.append(", sailorName=").append(sailorName);
        sb.append(", punchTime=").append(punchTime);
        sb.append(", dataType=").append(dataType);
        sb.append(", reason=").append(reason);
        sb.append(", iofTime=").append(iofTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}