package com.cetcme.springBootDemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ShipExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public ShipExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andShipIdIsNull() {
            addCriterion("`SHIP_ID` is null");
            return (Criteria) this;
        }

        public Criteria andShipIdIsNotNull() {
            addCriterion("`SHIP_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andShipIdEqualTo(Long value) {
            addCriterion("`SHIP_ID` =", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotEqualTo(Long value) {
            addCriterion("`SHIP_ID` <>", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdGreaterThan(Long value) {
            addCriterion("`SHIP_ID` >", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`SHIP_ID` >=", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdLessThan(Long value) {
            addCriterion("`SHIP_ID` <", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdLessThanOrEqualTo(Long value) {
            addCriterion("`SHIP_ID` <=", value, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdIn(List<Long> values) {
            addCriterion("`SHIP_ID` in", values, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotIn(List<Long> values) {
            addCriterion("`SHIP_ID` not in", values, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdBetween(Long value1, Long value2) {
            addCriterion("`SHIP_ID` between", value1, value2, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipIdNotBetween(Long value1, Long value2) {
            addCriterion("`SHIP_ID` not between", value1, value2, "shipId");
            return (Criteria) this;
        }

        public Criteria andShipNoIsNull() {
            addCriterion("`SHIP_NO` is null");
            return (Criteria) this;
        }

        public Criteria andShipNoIsNotNull() {
            addCriterion("`SHIP_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andShipNoEqualTo(String value) {
            addCriterion("`SHIP_NO` =", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotEqualTo(String value) {
            addCriterion("`SHIP_NO` <>", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoGreaterThan(String value) {
            addCriterion("`SHIP_NO` >", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoGreaterThanOrEqualTo(String value) {
            addCriterion("`SHIP_NO` >=", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoLessThan(String value) {
            addCriterion("`SHIP_NO` <", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoLessThanOrEqualTo(String value) {
            addCriterion("`SHIP_NO` <=", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoLike(String value) {
            addCriterion("`SHIP_NO` like", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotLike(String value) {
            addCriterion("`SHIP_NO` not like", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoIn(List<String> values) {
            addCriterion("`SHIP_NO` in", values, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotIn(List<String> values) {
            addCriterion("`SHIP_NO` not in", values, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoBetween(String value1, String value2) {
            addCriterion("`SHIP_NO` between", value1, value2, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotBetween(String value1, String value2) {
            addCriterion("`SHIP_NO` not between", value1, value2, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNameIsNull() {
            addCriterion("`SHIP_NAME` is null");
            return (Criteria) this;
        }

        public Criteria andShipNameIsNotNull() {
            addCriterion("`SHIP_NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andShipNameEqualTo(String value) {
            addCriterion("`SHIP_NAME` =", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameNotEqualTo(String value) {
            addCriterion("`SHIP_NAME` <>", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameGreaterThan(String value) {
            addCriterion("`SHIP_NAME` >", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameGreaterThanOrEqualTo(String value) {
            addCriterion("`SHIP_NAME` >=", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameLessThan(String value) {
            addCriterion("`SHIP_NAME` <", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameLessThanOrEqualTo(String value) {
            addCriterion("`SHIP_NAME` <=", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameLike(String value) {
            addCriterion("`SHIP_NAME` like", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameNotLike(String value) {
            addCriterion("`SHIP_NAME` not like", value, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameIn(List<String> values) {
            addCriterion("`SHIP_NAME` in", values, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameNotIn(List<String> values) {
            addCriterion("`SHIP_NAME` not in", values, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameBetween(String value1, String value2) {
            addCriterion("`SHIP_NAME` between", value1, value2, "shipName");
            return (Criteria) this;
        }

        public Criteria andShipNameNotBetween(String value1, String value2) {
            addCriterion("`SHIP_NAME` not between", value1, value2, "shipName");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("`DEVICE_ID` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("`DEVICE_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("`DEVICE_ID` =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("`DEVICE_ID` >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("`DEVICE_ID` <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("`DEVICE_ID` <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("`DEVICE_ID` in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("`DEVICE_ID` not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("`DEVICE_ID` not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andQrPicPathIsNull() {
            addCriterion("`QR_PIC_PATH` is null");
            return (Criteria) this;
        }

        public Criteria andQrPicPathIsNotNull() {
            addCriterion("`QR_PIC_PATH` is not null");
            return (Criteria) this;
        }

        public Criteria andQrPicPathEqualTo(String value) {
            addCriterion("`QR_PIC_PATH` =", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathNotEqualTo(String value) {
            addCriterion("`QR_PIC_PATH` <>", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathGreaterThan(String value) {
            addCriterion("`QR_PIC_PATH` >", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathGreaterThanOrEqualTo(String value) {
            addCriterion("`QR_PIC_PATH` >=", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathLessThan(String value) {
            addCriterion("`QR_PIC_PATH` <", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathLessThanOrEqualTo(String value) {
            addCriterion("`QR_PIC_PATH` <=", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathLike(String value) {
            addCriterion("`QR_PIC_PATH` like", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathNotLike(String value) {
            addCriterion("`QR_PIC_PATH` not like", value, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathIn(List<String> values) {
            addCriterion("`QR_PIC_PATH` in", values, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathNotIn(List<String> values) {
            addCriterion("`QR_PIC_PATH` not in", values, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathBetween(String value1, String value2) {
            addCriterion("`QR_PIC_PATH` between", value1, value2, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andQrPicPathNotBetween(String value1, String value2) {
            addCriterion("`QR_PIC_PATH` not between", value1, value2, "qrPicPath");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNull() {
            addCriterion("`OWNER_NAME` is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNotNull() {
            addCriterion("`OWNER_NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameEqualTo(String value) {
            addCriterion("`OWNER_NAME` =", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotEqualTo(String value) {
            addCriterion("`OWNER_NAME` <>", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThan(String value) {
            addCriterion("`OWNER_NAME` >", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("`OWNER_NAME` >=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThan(String value) {
            addCriterion("`OWNER_NAME` <", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThanOrEqualTo(String value) {
            addCriterion("`OWNER_NAME` <=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLike(String value) {
            addCriterion("`OWNER_NAME` like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotLike(String value) {
            addCriterion("`OWNER_NAME` not like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIn(List<String> values) {
            addCriterion("`OWNER_NAME` in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotIn(List<String> values) {
            addCriterion("`OWNER_NAME` not in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameBetween(String value1, String value2) {
            addCriterion("`OWNER_NAME` between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotBetween(String value1, String value2) {
            addCriterion("`OWNER_NAME` not between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoIsNull() {
            addCriterion("`OWNER_TEL_NO` is null");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoIsNotNull() {
            addCriterion("`OWNER_TEL_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoEqualTo(String value) {
            addCriterion("`OWNER_TEL_NO` =", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoNotEqualTo(String value) {
            addCriterion("`OWNER_TEL_NO` <>", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoGreaterThan(String value) {
            addCriterion("`OWNER_TEL_NO` >", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("`OWNER_TEL_NO` >=", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoLessThan(String value) {
            addCriterion("`OWNER_TEL_NO` <", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoLessThanOrEqualTo(String value) {
            addCriterion("`OWNER_TEL_NO` <=", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoLike(String value) {
            addCriterion("`OWNER_TEL_NO` like", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoNotLike(String value) {
            addCriterion("`OWNER_TEL_NO` not like", value, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoIn(List<String> values) {
            addCriterion("`OWNER_TEL_NO` in", values, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoNotIn(List<String> values) {
            addCriterion("`OWNER_TEL_NO` not in", values, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoBetween(String value1, String value2) {
            addCriterion("`OWNER_TEL_NO` between", value1, value2, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andOwnerTelNoNotBetween(String value1, String value2) {
            addCriterion("`OWNER_TEL_NO` not between", value1, value2, "ownerTelNo");
            return (Criteria) this;
        }

        public Criteria andPicNameIsNull() {
            addCriterion("`PIC_NAME` is null");
            return (Criteria) this;
        }

        public Criteria andPicNameIsNotNull() {
            addCriterion("`PIC_NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andPicNameEqualTo(String value) {
            addCriterion("`PIC_NAME` =", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameNotEqualTo(String value) {
            addCriterion("`PIC_NAME` <>", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameGreaterThan(String value) {
            addCriterion("`PIC_NAME` >", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameGreaterThanOrEqualTo(String value) {
            addCriterion("`PIC_NAME` >=", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameLessThan(String value) {
            addCriterion("`PIC_NAME` <", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameLessThanOrEqualTo(String value) {
            addCriterion("`PIC_NAME` <=", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameLike(String value) {
            addCriterion("`PIC_NAME` like", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameNotLike(String value) {
            addCriterion("`PIC_NAME` not like", value, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameIn(List<String> values) {
            addCriterion("`PIC_NAME` in", values, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameNotIn(List<String> values) {
            addCriterion("`PIC_NAME` not in", values, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameBetween(String value1, String value2) {
            addCriterion("`PIC_NAME` between", value1, value2, "picName");
            return (Criteria) this;
        }

        public Criteria andPicNameNotBetween(String value1, String value2) {
            addCriterion("`PIC_NAME` not between", value1, value2, "picName");
            return (Criteria) this;
        }

        public Criteria andPicTelNoIsNull() {
            addCriterion("`PIC_TEL_NO` is null");
            return (Criteria) this;
        }

        public Criteria andPicTelNoIsNotNull() {
            addCriterion("`PIC_TEL_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andPicTelNoEqualTo(String value) {
            addCriterion("`PIC_TEL_NO` =", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoNotEqualTo(String value) {
            addCriterion("`PIC_TEL_NO` <>", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoGreaterThan(String value) {
            addCriterion("`PIC_TEL_NO` >", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("`PIC_TEL_NO` >=", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoLessThan(String value) {
            addCriterion("`PIC_TEL_NO` <", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoLessThanOrEqualTo(String value) {
            addCriterion("`PIC_TEL_NO` <=", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoLike(String value) {
            addCriterion("`PIC_TEL_NO` like", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoNotLike(String value) {
            addCriterion("`PIC_TEL_NO` not like", value, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoIn(List<String> values) {
            addCriterion("`PIC_TEL_NO` in", values, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoNotIn(List<String> values) {
            addCriterion("`PIC_TEL_NO` not in", values, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoBetween(String value1, String value2) {
            addCriterion("`PIC_TEL_NO` between", value1, value2, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andPicTelNoNotBetween(String value1, String value2) {
            addCriterion("`PIC_TEL_NO` not between", value1, value2, "picTelNo");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("`BUSINESS_TYPE` is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("`BUSINESS_TYPE` is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("`BUSINESS_TYPE` =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("`BUSINESS_TYPE` <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("`BUSINESS_TYPE` >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`BUSINESS_TYPE` >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("`BUSINESS_TYPE` <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("`BUSINESS_TYPE` <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("`BUSINESS_TYPE` like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("`BUSINESS_TYPE` not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("`BUSINESS_TYPE` in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("`BUSINESS_TYPE` not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("`BUSINESS_TYPE` between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("`BUSINESS_TYPE` not between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andAttributionIsNull() {
            addCriterion("`ATTRIBUTION` is null");
            return (Criteria) this;
        }

        public Criteria andAttributionIsNotNull() {
            addCriterion("`ATTRIBUTION` is not null");
            return (Criteria) this;
        }

        public Criteria andAttributionEqualTo(String value) {
            addCriterion("`ATTRIBUTION` =", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotEqualTo(String value) {
            addCriterion("`ATTRIBUTION` <>", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionGreaterThan(String value) {
            addCriterion("`ATTRIBUTION` >", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionGreaterThanOrEqualTo(String value) {
            addCriterion("`ATTRIBUTION` >=", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLessThan(String value) {
            addCriterion("`ATTRIBUTION` <", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLessThanOrEqualTo(String value) {
            addCriterion("`ATTRIBUTION` <=", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLike(String value) {
            addCriterion("`ATTRIBUTION` like", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotLike(String value) {
            addCriterion("`ATTRIBUTION` not like", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionIn(List<String> values) {
            addCriterion("`ATTRIBUTION` in", values, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotIn(List<String> values) {
            addCriterion("`ATTRIBUTION` not in", values, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionBetween(String value1, String value2) {
            addCriterion("`ATTRIBUTION` between", value1, value2, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotBetween(String value1, String value2) {
            addCriterion("`ATTRIBUTION` not between", value1, value2, "attribution");
            return (Criteria) this;
        }

        public Criteria andRegPortIsNull() {
            addCriterion("`REG_PORT` is null");
            return (Criteria) this;
        }

        public Criteria andRegPortIsNotNull() {
            addCriterion("`REG_PORT` is not null");
            return (Criteria) this;
        }

        public Criteria andRegPortEqualTo(String value) {
            addCriterion("`REG_PORT` =", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortNotEqualTo(String value) {
            addCriterion("`REG_PORT` <>", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortGreaterThan(String value) {
            addCriterion("`REG_PORT` >", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortGreaterThanOrEqualTo(String value) {
            addCriterion("`REG_PORT` >=", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortLessThan(String value) {
            addCriterion("`REG_PORT` <", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortLessThanOrEqualTo(String value) {
            addCriterion("`REG_PORT` <=", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortLike(String value) {
            addCriterion("`REG_PORT` like", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortNotLike(String value) {
            addCriterion("`REG_PORT` not like", value, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortIn(List<String> values) {
            addCriterion("`REG_PORT` in", values, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortNotIn(List<String> values) {
            addCriterion("`REG_PORT` not in", values, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortBetween(String value1, String value2) {
            addCriterion("`REG_PORT` between", value1, value2, "regPort");
            return (Criteria) this;
        }

        public Criteria andRegPortNotBetween(String value1, String value2) {
            addCriterion("`REG_PORT` not between", value1, value2, "regPort");
            return (Criteria) this;
        }

        public Criteria andJobTypeIsNull() {
            addCriterion("`JOB_TYPE` is null");
            return (Criteria) this;
        }

        public Criteria andJobTypeIsNotNull() {
            addCriterion("`JOB_TYPE` is not null");
            return (Criteria) this;
        }

        public Criteria andJobTypeEqualTo(String value) {
            addCriterion("`JOB_TYPE` =", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotEqualTo(String value) {
            addCriterion("`JOB_TYPE` <>", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeGreaterThan(String value) {
            addCriterion("`JOB_TYPE` >", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`JOB_TYPE` >=", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLessThan(String value) {
            addCriterion("`JOB_TYPE` <", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLessThanOrEqualTo(String value) {
            addCriterion("`JOB_TYPE` <=", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLike(String value) {
            addCriterion("`JOB_TYPE` like", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotLike(String value) {
            addCriterion("`JOB_TYPE` not like", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeIn(List<String> values) {
            addCriterion("`JOB_TYPE` in", values, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotIn(List<String> values) {
            addCriterion("`JOB_TYPE` not in", values, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeBetween(String value1, String value2) {
            addCriterion("`JOB_TYPE` between", value1, value2, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotBetween(String value1, String value2) {
            addCriterion("`JOB_TYPE` not between", value1, value2, "jobType");
            return (Criteria) this;
        }

        public Criteria andShipAgeIsNull() {
            addCriterion("`SHIP_AGE` is null");
            return (Criteria) this;
        }

        public Criteria andShipAgeIsNotNull() {
            addCriterion("`SHIP_AGE` is not null");
            return (Criteria) this;
        }

        public Criteria andShipAgeEqualTo(Integer value) {
            addCriterion("`SHIP_AGE` =", value, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeNotEqualTo(Integer value) {
            addCriterion("`SHIP_AGE` <>", value, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeGreaterThan(Integer value) {
            addCriterion("`SHIP_AGE` >", value, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`SHIP_AGE` >=", value, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeLessThan(Integer value) {
            addCriterion("`SHIP_AGE` <", value, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeLessThanOrEqualTo(Integer value) {
            addCriterion("`SHIP_AGE` <=", value, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeIn(List<Integer> values) {
            addCriterion("`SHIP_AGE` in", values, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeNotIn(List<Integer> values) {
            addCriterion("`SHIP_AGE` not in", values, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeBetween(Integer value1, Integer value2) {
            addCriterion("`SHIP_AGE` between", value1, value2, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("`SHIP_AGE` not between", value1, value2, "shipAge");
            return (Criteria) this;
        }

        public Criteria andShipLengthIsNull() {
            addCriterion("`SHIP_LENGTH` is null");
            return (Criteria) this;
        }

        public Criteria andShipLengthIsNotNull() {
            addCriterion("`SHIP_LENGTH` is not null");
            return (Criteria) this;
        }

        public Criteria andShipLengthEqualTo(Double value) {
            addCriterion("`SHIP_LENGTH` =", value, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthNotEqualTo(Double value) {
            addCriterion("`SHIP_LENGTH` <>", value, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthGreaterThan(Double value) {
            addCriterion("`SHIP_LENGTH` >", value, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("`SHIP_LENGTH` >=", value, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthLessThan(Double value) {
            addCriterion("`SHIP_LENGTH` <", value, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthLessThanOrEqualTo(Double value) {
            addCriterion("`SHIP_LENGTH` <=", value, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthIn(List<Double> values) {
            addCriterion("`SHIP_LENGTH` in", values, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthNotIn(List<Double> values) {
            addCriterion("`SHIP_LENGTH` not in", values, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthBetween(Double value1, Double value2) {
            addCriterion("`SHIP_LENGTH` between", value1, value2, "shipLength");
            return (Criteria) this;
        }

        public Criteria andShipLengthNotBetween(Double value1, Double value2) {
            addCriterion("`SHIP_LENGTH` not between", value1, value2, "shipLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthIsNull() {
            addCriterion("`UPPER_DECK_LENGTH` is null");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthIsNotNull() {
            addCriterion("`UPPER_DECK_LENGTH` is not null");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthEqualTo(Double value) {
            addCriterion("`UPPER_DECK_LENGTH` =", value, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthNotEqualTo(Double value) {
            addCriterion("`UPPER_DECK_LENGTH` <>", value, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthGreaterThan(Double value) {
            addCriterion("`UPPER_DECK_LENGTH` >", value, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("`UPPER_DECK_LENGTH` >=", value, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthLessThan(Double value) {
            addCriterion("`UPPER_DECK_LENGTH` <", value, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthLessThanOrEqualTo(Double value) {
            addCriterion("`UPPER_DECK_LENGTH` <=", value, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthIn(List<Double> values) {
            addCriterion("`UPPER_DECK_LENGTH` in", values, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthNotIn(List<Double> values) {
            addCriterion("`UPPER_DECK_LENGTH` not in", values, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthBetween(Double value1, Double value2) {
            addCriterion("`UPPER_DECK_LENGTH` between", value1, value2, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andUpperDeckLengthNotBetween(Double value1, Double value2) {
            addCriterion("`UPPER_DECK_LENGTH` not between", value1, value2, "upperDeckLength");
            return (Criteria) this;
        }

        public Criteria andShipBreadthIsNull() {
            addCriterion("`SHIP_BREADTH` is null");
            return (Criteria) this;
        }

        public Criteria andShipBreadthIsNotNull() {
            addCriterion("`SHIP_BREADTH` is not null");
            return (Criteria) this;
        }

        public Criteria andShipBreadthEqualTo(Double value) {
            addCriterion("`SHIP_BREADTH` =", value, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthNotEqualTo(Double value) {
            addCriterion("`SHIP_BREADTH` <>", value, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthGreaterThan(Double value) {
            addCriterion("`SHIP_BREADTH` >", value, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthGreaterThanOrEqualTo(Double value) {
            addCriterion("`SHIP_BREADTH` >=", value, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthLessThan(Double value) {
            addCriterion("`SHIP_BREADTH` <", value, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthLessThanOrEqualTo(Double value) {
            addCriterion("`SHIP_BREADTH` <=", value, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthIn(List<Double> values) {
            addCriterion("`SHIP_BREADTH` in", values, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthNotIn(List<Double> values) {
            addCriterion("`SHIP_BREADTH` not in", values, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthBetween(Double value1, Double value2) {
            addCriterion("`SHIP_BREADTH` between", value1, value2, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipBreadthNotBetween(Double value1, Double value2) {
            addCriterion("`SHIP_BREADTH` not between", value1, value2, "shipBreadth");
            return (Criteria) this;
        }

        public Criteria andShipDepthIsNull() {
            addCriterion("`SHIP_DEPTH` is null");
            return (Criteria) this;
        }

        public Criteria andShipDepthIsNotNull() {
            addCriterion("`SHIP_DEPTH` is not null");
            return (Criteria) this;
        }

        public Criteria andShipDepthEqualTo(Double value) {
            addCriterion("`SHIP_DEPTH` =", value, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthNotEqualTo(Double value) {
            addCriterion("`SHIP_DEPTH` <>", value, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthGreaterThan(Double value) {
            addCriterion("`SHIP_DEPTH` >", value, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthGreaterThanOrEqualTo(Double value) {
            addCriterion("`SHIP_DEPTH` >=", value, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthLessThan(Double value) {
            addCriterion("`SHIP_DEPTH` <", value, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthLessThanOrEqualTo(Double value) {
            addCriterion("`SHIP_DEPTH` <=", value, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthIn(List<Double> values) {
            addCriterion("`SHIP_DEPTH` in", values, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthNotIn(List<Double> values) {
            addCriterion("`SHIP_DEPTH` not in", values, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthBetween(Double value1, Double value2) {
            addCriterion("`SHIP_DEPTH` between", value1, value2, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipDepthNotBetween(Double value1, Double value2) {
            addCriterion("`SHIP_DEPTH` not between", value1, value2, "shipDepth");
            return (Criteria) this;
        }

        public Criteria andShipMaterialIsNull() {
            addCriterion("`SHIP_MATERIAL` is null");
            return (Criteria) this;
        }

        public Criteria andShipMaterialIsNotNull() {
            addCriterion("`SHIP_MATERIAL` is not null");
            return (Criteria) this;
        }

        public Criteria andShipMaterialEqualTo(String value) {
            addCriterion("`SHIP_MATERIAL` =", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialNotEqualTo(String value) {
            addCriterion("`SHIP_MATERIAL` <>", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialGreaterThan(String value) {
            addCriterion("`SHIP_MATERIAL` >", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("`SHIP_MATERIAL` >=", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialLessThan(String value) {
            addCriterion("`SHIP_MATERIAL` <", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialLessThanOrEqualTo(String value) {
            addCriterion("`SHIP_MATERIAL` <=", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialLike(String value) {
            addCriterion("`SHIP_MATERIAL` like", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialNotLike(String value) {
            addCriterion("`SHIP_MATERIAL` not like", value, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialIn(List<String> values) {
            addCriterion("`SHIP_MATERIAL` in", values, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialNotIn(List<String> values) {
            addCriterion("`SHIP_MATERIAL` not in", values, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialBetween(String value1, String value2) {
            addCriterion("`SHIP_MATERIAL` between", value1, value2, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipMaterialNotBetween(String value1, String value2) {
            addCriterion("`SHIP_MATERIAL` not between", value1, value2, "shipMaterial");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateIsNull() {
            addCriterion("`SHIP_BUILD_DATE` is null");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateIsNotNull() {
            addCriterion("`SHIP_BUILD_DATE` is not null");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateEqualTo(Date value) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` =", value, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` <>", value, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateGreaterThan(Date value) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` >", value, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` >=", value, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateLessThan(Date value) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` <", value, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` <=", value, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateIn(List<Date> values) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` in", values, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` not in", values, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` between", value1, value2, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andShipBuildDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`SHIP_BUILD_DATE` not between", value1, value2, "shipBuildDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateIsNull() {
            addCriterion("`CARD_MAKE_DATE` is null");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateIsNotNull() {
            addCriterion("`CARD_MAKE_DATE` is not null");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateEqualTo(Date value) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` =", value, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` <>", value, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateGreaterThan(Date value) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` >", value, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` >=", value, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateLessThan(Date value) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` <", value, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` <=", value, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateIn(List<Date> values) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` in", values, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` not in", values, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` between", value1, value2, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCardMakeDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`CARD_MAKE_DATE` not between", value1, value2, "cardMakeDate");
            return (Criteria) this;
        }

        public Criteria andCallLettersIsNull() {
            addCriterion("`CALL_LETTERS` is null");
            return (Criteria) this;
        }

        public Criteria andCallLettersIsNotNull() {
            addCriterion("`CALL_LETTERS` is not null");
            return (Criteria) this;
        }

        public Criteria andCallLettersEqualTo(String value) {
            addCriterion("`CALL_LETTERS` =", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersNotEqualTo(String value) {
            addCriterion("`CALL_LETTERS` <>", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersGreaterThan(String value) {
            addCriterion("`CALL_LETTERS` >", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersGreaterThanOrEqualTo(String value) {
            addCriterion("`CALL_LETTERS` >=", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersLessThan(String value) {
            addCriterion("`CALL_LETTERS` <", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersLessThanOrEqualTo(String value) {
            addCriterion("`CALL_LETTERS` <=", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersLike(String value) {
            addCriterion("`CALL_LETTERS` like", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersNotLike(String value) {
            addCriterion("`CALL_LETTERS` not like", value, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersIn(List<String> values) {
            addCriterion("`CALL_LETTERS` in", values, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersNotIn(List<String> values) {
            addCriterion("`CALL_LETTERS` not in", values, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersBetween(String value1, String value2) {
            addCriterion("`CALL_LETTERS` between", value1, value2, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCallLettersNotBetween(String value1, String value2) {
            addCriterion("`CALL_LETTERS` not between", value1, value2, "callLetters");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateIsNull() {
            addCriterion("`CFS_START_DATE` is null");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateIsNotNull() {
            addCriterion("`CFS_START_DATE` is not null");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_START_DATE` =", value, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_START_DATE` <>", value, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("`CFS_START_DATE` >", value, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_START_DATE` >=", value, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateLessThan(Date value) {
            addCriterionForJDBCDate("`CFS_START_DATE` <", value, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_START_DATE` <=", value, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("`CFS_START_DATE` in", values, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("`CFS_START_DATE` not in", values, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`CFS_START_DATE` between", value1, value2, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`CFS_START_DATE` not between", value1, value2, "cfsStartDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateIsNull() {
            addCriterion("`CFS_END_DATE` is null");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateIsNotNull() {
            addCriterion("`CFS_END_DATE` is not null");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_END_DATE` =", value, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_END_DATE` <>", value, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("`CFS_END_DATE` >", value, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_END_DATE` >=", value, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateLessThan(Date value) {
            addCriterionForJDBCDate("`CFS_END_DATE` <", value, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`CFS_END_DATE` <=", value, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("`CFS_END_DATE` in", values, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("`CFS_END_DATE` not in", values, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`CFS_END_DATE` between", value1, value2, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andCfsEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`CFS_END_DATE` not between", value1, value2, "cfsEndDate");
            return (Criteria) this;
        }

        public Criteria andInstallerNameIsNull() {
            addCriterion("`INSTALLER_NAME` is null");
            return (Criteria) this;
        }

        public Criteria andInstallerNameIsNotNull() {
            addCriterion("`INSTALLER_NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andInstallerNameEqualTo(String value) {
            addCriterion("`INSTALLER_NAME` =", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameNotEqualTo(String value) {
            addCriterion("`INSTALLER_NAME` <>", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameGreaterThan(String value) {
            addCriterion("`INSTALLER_NAME` >", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameGreaterThanOrEqualTo(String value) {
            addCriterion("`INSTALLER_NAME` >=", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameLessThan(String value) {
            addCriterion("`INSTALLER_NAME` <", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameLessThanOrEqualTo(String value) {
            addCriterion("`INSTALLER_NAME` <=", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameLike(String value) {
            addCriterion("`INSTALLER_NAME` like", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameNotLike(String value) {
            addCriterion("`INSTALLER_NAME` not like", value, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameIn(List<String> values) {
            addCriterion("`INSTALLER_NAME` in", values, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameNotIn(List<String> values) {
            addCriterion("`INSTALLER_NAME` not in", values, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameBetween(String value1, String value2) {
            addCriterion("`INSTALLER_NAME` between", value1, value2, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerNameNotBetween(String value1, String value2) {
            addCriterion("`INSTALLER_NAME` not between", value1, value2, "installerName");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoIsNull() {
            addCriterion("`INSTALLER_TEL_NO` is null");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoIsNotNull() {
            addCriterion("`INSTALLER_TEL_NO` is not null");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoEqualTo(String value) {
            addCriterion("`INSTALLER_TEL_NO` =", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoNotEqualTo(String value) {
            addCriterion("`INSTALLER_TEL_NO` <>", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoGreaterThan(String value) {
            addCriterion("`INSTALLER_TEL_NO` >", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("`INSTALLER_TEL_NO` >=", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoLessThan(String value) {
            addCriterion("`INSTALLER_TEL_NO` <", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoLessThanOrEqualTo(String value) {
            addCriterion("`INSTALLER_TEL_NO` <=", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoLike(String value) {
            addCriterion("`INSTALLER_TEL_NO` like", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoNotLike(String value) {
            addCriterion("`INSTALLER_TEL_NO` not like", value, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoIn(List<String> values) {
            addCriterion("`INSTALLER_TEL_NO` in", values, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoNotIn(List<String> values) {
            addCriterion("`INSTALLER_TEL_NO` not in", values, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoBetween(String value1, String value2) {
            addCriterion("`INSTALLER_TEL_NO` between", value1, value2, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallerTelNoNotBetween(String value1, String value2) {
            addCriterion("`INSTALLER_TEL_NO` not between", value1, value2, "installerTelNo");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceIsNull() {
            addCriterion("`INSTALL_PLACE` is null");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceIsNotNull() {
            addCriterion("`INSTALL_PLACE` is not null");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceEqualTo(String value) {
            addCriterion("`INSTALL_PLACE` =", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceNotEqualTo(String value) {
            addCriterion("`INSTALL_PLACE` <>", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceGreaterThan(String value) {
            addCriterion("`INSTALL_PLACE` >", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("`INSTALL_PLACE` >=", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceLessThan(String value) {
            addCriterion("`INSTALL_PLACE` <", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceLessThanOrEqualTo(String value) {
            addCriterion("`INSTALL_PLACE` <=", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceLike(String value) {
            addCriterion("`INSTALL_PLACE` like", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceNotLike(String value) {
            addCriterion("`INSTALL_PLACE` not like", value, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceIn(List<String> values) {
            addCriterion("`INSTALL_PLACE` in", values, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceNotIn(List<String> values) {
            addCriterion("`INSTALL_PLACE` not in", values, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceBetween(String value1, String value2) {
            addCriterion("`INSTALL_PLACE` between", value1, value2, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallPlaceNotBetween(String value1, String value2) {
            addCriterion("`INSTALL_PLACE` not between", value1, value2, "installPlace");
            return (Criteria) this;
        }

        public Criteria andInstallTimeIsNull() {
            addCriterion("`INSTALL_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andInstallTimeIsNotNull() {
            addCriterion("`INSTALL_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andInstallTimeEqualTo(Date value) {
            addCriterion("`INSTALL_TIME` =", value, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeNotEqualTo(Date value) {
            addCriterion("`INSTALL_TIME` <>", value, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeGreaterThan(Date value) {
            addCriterion("`INSTALL_TIME` >", value, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`INSTALL_TIME` >=", value, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeLessThan(Date value) {
            addCriterion("`INSTALL_TIME` <", value, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeLessThanOrEqualTo(Date value) {
            addCriterion("`INSTALL_TIME` <=", value, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeIn(List<Date> values) {
            addCriterion("`INSTALL_TIME` in", values, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeNotIn(List<Date> values) {
            addCriterion("`INSTALL_TIME` not in", values, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeBetween(Date value1, Date value2) {
            addCriterion("`INSTALL_TIME` between", value1, value2, "installTime");
            return (Criteria) this;
        }

        public Criteria andInstallTimeNotBetween(Date value1, Date value2) {
            addCriterion("`INSTALL_TIME` not between", value1, value2, "installTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("`CREATE_USER_ID` is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("`CREATE_USER_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("`CREATE_USER_ID` >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("`CREATE_USER_ID` <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("`CREATE_USER_ID` <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("`CREATE_USER_ID` in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("`CREATE_USER_ID` not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("`CREATE_USER_ID` between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("`CREATE_USER_ID` not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`CREATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`CREATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`CREATE_TIME` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`CREATE_TIME` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`CREATE_TIME` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`CREATE_TIME` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`CREATE_TIME` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`CREATE_TIME` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`CREATE_TIME` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("`UPDATE_USER_ID` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("`UPDATE_USER_ID` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Long value) {
            addCriterion("`UPDATE_USER_ID` >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Long value) {
            addCriterion("`UPDATE_USER_ID` <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("`UPDATE_USER_ID` <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Long> values) {
            addCriterion("`UPDATE_USER_ID` in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Long> values) {
            addCriterion("`UPDATE_USER_ID` not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("`UPDATE_USER_ID` between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("`UPDATE_USER_ID` not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`UPDATE_TIME` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`UPDATE_TIME` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`UPDATE_TIME` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`UPDATE_TIME` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`UPDATE_TIME` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`UPDATE_TIME` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`UPDATE_TIME` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDataSourceIsNull() {
            addCriterion("`DATA_SOURCE` is null");
            return (Criteria) this;
        }

        public Criteria andDataSourceIsNotNull() {
            addCriterion("`DATA_SOURCE` is not null");
            return (Criteria) this;
        }

        public Criteria andDataSourceEqualTo(Integer value) {
            addCriterion("`DATA_SOURCE` =", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotEqualTo(Integer value) {
            addCriterion("`DATA_SOURCE` <>", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceGreaterThan(Integer value) {
            addCriterion("`DATA_SOURCE` >", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("`DATA_SOURCE` >=", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceLessThan(Integer value) {
            addCriterion("`DATA_SOURCE` <", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceLessThanOrEqualTo(Integer value) {
            addCriterion("`DATA_SOURCE` <=", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceIn(List<Integer> values) {
            addCriterion("`DATA_SOURCE` in", values, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotIn(List<Integer> values) {
            addCriterion("`DATA_SOURCE` not in", values, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceBetween(Integer value1, Integer value2) {
            addCriterion("`DATA_SOURCE` between", value1, value2, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("`DATA_SOURCE` not between", value1, value2, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("`DEL_FLAG` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("`DEL_FLAG` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("`DEL_FLAG` >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("`DEL_FLAG` <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("`DEL_FLAG` <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("`DEL_FLAG` not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`DEL_FLAG` not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ship
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}