package com.cetcme.springBootDemo.domain;

import java.io.Serializable;
import java.util.Date;

public class Ship implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_ID
     *
     * @mbggenerated
     */
    private Long shipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_NO
     *
     * @mbggenerated
     */
    private String shipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_NAME
     *
     * @mbggenerated
     */
    private String shipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.DEVICE_ID
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.QR_PIC_PATH
     *
     * @mbggenerated
     */
    private String qrPicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.OWNER_NAME
     *
     * @mbggenerated
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.OWNER_TEL_NO
     *
     * @mbggenerated
     */
    private String ownerTelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.PIC_NAME
     *
     * @mbggenerated
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.PIC_TEL_NO
     *
     * @mbggenerated
     */
    private String picTelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.ATTRIBUTION
     *
     * @mbggenerated
     */
    private String attribution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.REG_PORT
     *
     * @mbggenerated
     */
    private String regPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.JOB_TYPE
     *
     * @mbggenerated
     */
    private String jobType;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.PERSON_RATED
     *
     * @mbggenerated
     */
    private Integer personRated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_AGE
     *
     * @mbggenerated
     */
    private Integer shipAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_LENGTH
     *
     * @mbggenerated
     */
    private Double shipLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.UPPER_DECK_LENGTH
     *
     * @mbggenerated
     */
    private Double upperDeckLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_BREADTH
     *
     * @mbggenerated
     */
    private Double shipBreadth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_DEPTH
     *
     * @mbggenerated
     */
    private Double shipDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_MATERIAL
     *
     * @mbggenerated
     */
    private String shipMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.SHIP_BUILD_DATE
     *
     * @mbggenerated
     */
    private Date shipBuildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.CARD_MAKE_DATE
     *
     * @mbggenerated
     */
    private Date cardMakeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.CALL_LETTERS
     *
     * @mbggenerated
     */
    private String callLetters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.CFS_START_DATE
     *
     * @mbggenerated
     */
    private Date cfsStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.CFS_END_DATE
     *
     * @mbggenerated
     */
    private Date cfsEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.INSTALLER_NAME
     *
     * @mbggenerated
     */
    private String installerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.INSTALLER_TEL_NO
     *
     * @mbggenerated
     */
    private String installerTelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.INSTALL_PLACE
     *
     * @mbggenerated
     */
    private String installPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.INSTALL_TIME
     *
     * @mbggenerated
     */
    private Date installTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.DATA_SOURCE
     *
     * @mbggenerated
     */
    private Integer dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ship.DEL_FLAG
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_ID
     *
     * @return the value of t_ship.SHIP_ID
     *
     * @mbggenerated
     */
    public Long getShipId() {
        return shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_ID
     *
     * @param shipId the value for t_ship.SHIP_ID
     *
     * @mbggenerated
     */
    public void setShipId(Long shipId) {
        this.shipId = shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_NO
     *
     * @return the value of t_ship.SHIP_NO
     *
     * @mbggenerated
     */
    public String getShipNo() {
        return shipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_NO
     *
     * @param shipNo the value for t_ship.SHIP_NO
     *
     * @mbggenerated
     */
    public void setShipNo(String shipNo) {
        this.shipNo = shipNo == null ? null : shipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_NAME
     *
     * @return the value of t_ship.SHIP_NAME
     *
     * @mbggenerated
     */
    public String getShipName() {
        return shipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_NAME
     *
     * @param shipName the value for t_ship.SHIP_NAME
     *
     * @mbggenerated
     */
    public void setShipName(String shipName) {
        this.shipName = shipName == null ? null : shipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.DEVICE_ID
     *
     * @return the value of t_ship.DEVICE_ID
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.DEVICE_ID
     *
     * @param deviceId the value for t_ship.DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.QR_PIC_PATH
     *
     * @return the value of t_ship.QR_PIC_PATH
     *
     * @mbggenerated
     */
    public String getQrPicPath() {
        return qrPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.QR_PIC_PATH
     *
     * @param qrPicPath the value for t_ship.QR_PIC_PATH
     *
     * @mbggenerated
     */
    public void setQrPicPath(String qrPicPath) {
        this.qrPicPath = qrPicPath == null ? null : qrPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.OWNER_NAME
     *
     * @return the value of t_ship.OWNER_NAME
     *
     * @mbggenerated
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.OWNER_NAME
     *
     * @param ownerName the value for t_ship.OWNER_NAME
     *
     * @mbggenerated
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.OWNER_TEL_NO
     *
     * @return the value of t_ship.OWNER_TEL_NO
     *
     * @mbggenerated
     */
    public String getOwnerTelNo() {
        return ownerTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.OWNER_TEL_NO
     *
     * @param ownerTelNo the value for t_ship.OWNER_TEL_NO
     *
     * @mbggenerated
     */
    public void setOwnerTelNo(String ownerTelNo) {
        this.ownerTelNo = ownerTelNo == null ? null : ownerTelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.PIC_NAME
     *
     * @return the value of t_ship.PIC_NAME
     *
     * @mbggenerated
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.PIC_NAME
     *
     * @param picName the value for t_ship.PIC_NAME
     *
     * @mbggenerated
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.PIC_TEL_NO
     *
     * @return the value of t_ship.PIC_TEL_NO
     *
     * @mbggenerated
     */
    public String getPicTelNo() {
        return picTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.PIC_TEL_NO
     *
     * @param picTelNo the value for t_ship.PIC_TEL_NO
     *
     * @mbggenerated
     */
    public void setPicTelNo(String picTelNo) {
        this.picTelNo = picTelNo == null ? null : picTelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.BUSINESS_TYPE
     *
     * @return the value of t_ship.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.BUSINESS_TYPE
     *
     * @param businessType the value for t_ship.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.ATTRIBUTION
     *
     * @return the value of t_ship.ATTRIBUTION
     *
     * @mbggenerated
     */
    public String getAttribution() {
        return attribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.ATTRIBUTION
     *
     * @param attribution the value for t_ship.ATTRIBUTION
     *
     * @mbggenerated
     */
    public void setAttribution(String attribution) {
        this.attribution = attribution == null ? null : attribution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.REG_PORT
     *
     * @return the value of t_ship.REG_PORT
     *
     * @mbggenerated
     */
    public String getRegPort() {
        return regPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.REG_PORT
     *
     * @param regPort the value for t_ship.REG_PORT
     *
     * @mbggenerated
     */
    public void setRegPort(String regPort) {
        this.regPort = regPort == null ? null : regPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.PERSON_RATED
     *
     * @return the value of t_ship.PERSON_RATED
     *
     * @mbggenerated
     */
    public Integer getPersonRated() {
        return personRated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.PERSON_RATED
     *
     * @param jobType the value for t_ship.PERSON_RATED
     *
     * @mbggenerated
     */
    public void setPersonRated(Integer personRated) {
    	this.personRated = personRated;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.JOB_TYPE
     *
     * @return the value of t_ship.JOB_TYPE
     *
     * @mbggenerated
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.JOB_TYPE
     *
     * @param jobType the value for t_ship.JOB_TYPE
     *
     * @mbggenerated
     */
    public void setJobType(String jobType) {
        this.jobType = jobType == null ? null : jobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_AGE
     *
     * @return the value of t_ship.SHIP_AGE
     *
     * @mbggenerated
     */
    public Integer getShipAge() {
        return shipAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_AGE
     *
     * @param shipAge the value for t_ship.SHIP_AGE
     *
     * @mbggenerated
     */
    public void setShipAge(Integer shipAge) {
        this.shipAge = shipAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_LENGTH
     *
     * @return the value of t_ship.SHIP_LENGTH
     *
     * @mbggenerated
     */
    public Double getShipLength() {
        return shipLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_LENGTH
     *
     * @param shipLength the value for t_ship.SHIP_LENGTH
     *
     * @mbggenerated
     */
    public void setShipLength(Double shipLength) {
        this.shipLength = shipLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.UPPER_DECK_LENGTH
     *
     * @return the value of t_ship.UPPER_DECK_LENGTH
     *
     * @mbggenerated
     */
    public Double getUpperDeckLength() {
        return upperDeckLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.UPPER_DECK_LENGTH
     *
     * @param upperDeckLength the value for t_ship.UPPER_DECK_LENGTH
     *
     * @mbggenerated
     */
    public void setUpperDeckLength(Double upperDeckLength) {
        this.upperDeckLength = upperDeckLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_BREADTH
     *
     * @return the value of t_ship.SHIP_BREADTH
     *
     * @mbggenerated
     */
    public Double getShipBreadth() {
        return shipBreadth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_BREADTH
     *
     * @param shipBreadth the value for t_ship.SHIP_BREADTH
     *
     * @mbggenerated
     */
    public void setShipBreadth(Double shipBreadth) {
        this.shipBreadth = shipBreadth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_DEPTH
     *
     * @return the value of t_ship.SHIP_DEPTH
     *
     * @mbggenerated
     */
    public Double getShipDepth() {
        return shipDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_DEPTH
     *
     * @param shipDepth the value for t_ship.SHIP_DEPTH
     *
     * @mbggenerated
     */
    public void setShipDepth(Double shipDepth) {
        this.shipDepth = shipDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_MATERIAL
     *
     * @return the value of t_ship.SHIP_MATERIAL
     *
     * @mbggenerated
     */
    public String getShipMaterial() {
        return shipMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_MATERIAL
     *
     * @param shipMaterial the value for t_ship.SHIP_MATERIAL
     *
     * @mbggenerated
     */
    public void setShipMaterial(String shipMaterial) {
        this.shipMaterial = shipMaterial == null ? null : shipMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.SHIP_BUILD_DATE
     *
     * @return the value of t_ship.SHIP_BUILD_DATE
     *
     * @mbggenerated
     */
    public Date getShipBuildDate() {
        return shipBuildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.SHIP_BUILD_DATE
     *
     * @param shipBuildDate the value for t_ship.SHIP_BUILD_DATE
     *
     * @mbggenerated
     */
    public void setShipBuildDate(Date shipBuildDate) {
        this.shipBuildDate = shipBuildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.CARD_MAKE_DATE
     *
     * @return the value of t_ship.CARD_MAKE_DATE
     *
     * @mbggenerated
     */
    public Date getCardMakeDate() {
        return cardMakeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.CARD_MAKE_DATE
     *
     * @param cardMakeDate the value for t_ship.CARD_MAKE_DATE
     *
     * @mbggenerated
     */
    public void setCardMakeDate(Date cardMakeDate) {
        this.cardMakeDate = cardMakeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.CALL_LETTERS
     *
     * @return the value of t_ship.CALL_LETTERS
     *
     * @mbggenerated
     */
    public String getCallLetters() {
        return callLetters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.CALL_LETTERS
     *
     * @param callLetters the value for t_ship.CALL_LETTERS
     *
     * @mbggenerated
     */
    public void setCallLetters(String callLetters) {
        this.callLetters = callLetters == null ? null : callLetters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.CFS_START_DATE
     *
     * @return the value of t_ship.CFS_START_DATE
     *
     * @mbggenerated
     */
    public Date getCfsStartDate() {
        return cfsStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.CFS_START_DATE
     *
     * @param cfsStartDate the value for t_ship.CFS_START_DATE
     *
     * @mbggenerated
     */
    public void setCfsStartDate(Date cfsStartDate) {
        this.cfsStartDate = cfsStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.CFS_END_DATE
     *
     * @return the value of t_ship.CFS_END_DATE
     *
     * @mbggenerated
     */
    public Date getCfsEndDate() {
        return cfsEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.CFS_END_DATE
     *
     * @param cfsEndDate the value for t_ship.CFS_END_DATE
     *
     * @mbggenerated
     */
    public void setCfsEndDate(Date cfsEndDate) {
        this.cfsEndDate = cfsEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.INSTALLER_NAME
     *
     * @return the value of t_ship.INSTALLER_NAME
     *
     * @mbggenerated
     */
    public String getInstallerName() {
        return installerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.INSTALLER_NAME
     *
     * @param installerName the value for t_ship.INSTALLER_NAME
     *
     * @mbggenerated
     */
    public void setInstallerName(String installerName) {
        this.installerName = installerName == null ? null : installerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.INSTALLER_TEL_NO
     *
     * @return the value of t_ship.INSTALLER_TEL_NO
     *
     * @mbggenerated
     */
    public String getInstallerTelNo() {
        return installerTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.INSTALLER_TEL_NO
     *
     * @param installerTelNo the value for t_ship.INSTALLER_TEL_NO
     *
     * @mbggenerated
     */
    public void setInstallerTelNo(String installerTelNo) {
        this.installerTelNo = installerTelNo == null ? null : installerTelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.INSTALL_PLACE
     *
     * @return the value of t_ship.INSTALL_PLACE
     *
     * @mbggenerated
     */
    public String getInstallPlace() {
        return installPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.INSTALL_PLACE
     *
     * @param installPlace the value for t_ship.INSTALL_PLACE
     *
     * @mbggenerated
     */
    public void setInstallPlace(String installPlace) {
        this.installPlace = installPlace == null ? null : installPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.INSTALL_TIME
     *
     * @return the value of t_ship.INSTALL_TIME
     *
     * @mbggenerated
     */
    public Date getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.INSTALL_TIME
     *
     * @param installTime the value for t_ship.INSTALL_TIME
     *
     * @mbggenerated
     */
    public void setInstallTime(Date installTime) {
        this.installTime = installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.CREATE_USER_ID
     *
     * @return the value of t_ship.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.CREATE_USER_ID
     *
     * @param createUserId the value for t_ship.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.CREATE_TIME
     *
     * @return the value of t_ship.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.CREATE_TIME
     *
     * @param createTime the value for t_ship.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.UPDATE_USER_ID
     *
     * @return the value of t_ship.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.UPDATE_USER_ID
     *
     * @param updateUserId the value for t_ship.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.UPDATE_TIME
     *
     * @return the value of t_ship.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.UPDATE_TIME
     *
     * @param updateTime the value for t_ship.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.DATA_SOURCE
     *
     * @return the value of t_ship.DATA_SOURCE
     *
     * @mbggenerated
     */
    public Integer getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.DATA_SOURCE
     *
     * @param dataSource the value for t_ship.DATA_SOURCE
     *
     * @mbggenerated
     */
    public void setDataSource(Integer dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ship.DEL_FLAG
     *
     * @return the value of t_ship.DEL_FLAG
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ship.DEL_FLAG
     *
     * @param delFlag the value for t_ship.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ship
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shipId=").append(shipId);
        sb.append(", shipNo=").append(shipNo);
        sb.append(", shipName=").append(shipName);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", qrPicPath=").append(qrPicPath);
        sb.append(", ownerName=").append(ownerName);
        sb.append(", ownerTelNo=").append(ownerTelNo);
        sb.append(", picName=").append(picName);
        sb.append(", picTelNo=").append(picTelNo);
        sb.append(", businessType=").append(businessType);
        sb.append(", attribution=").append(attribution);
        sb.append(", regPort=").append(regPort);
        sb.append(", jobType=").append(jobType);
        sb.append(", shipAge=").append(shipAge);
        sb.append(", shipLength=").append(shipLength);
        sb.append(", upperDeckLength=").append(upperDeckLength);
        sb.append(", shipBreadth=").append(shipBreadth);
        sb.append(", shipDepth=").append(shipDepth);
        sb.append(", shipMaterial=").append(shipMaterial);
        sb.append(", shipBuildDate=").append(shipBuildDate);
        sb.append(", cardMakeDate=").append(cardMakeDate);
        sb.append(", callLetters=").append(callLetters);
        sb.append(", cfsStartDate=").append(cfsStartDate);
        sb.append(", cfsEndDate=").append(cfsEndDate);
        sb.append(", installerName=").append(installerName);
        sb.append(", installerTelNo=").append(installerTelNo);
        sb.append(", installPlace=").append(installPlace);
        sb.append(", installTime=").append(installTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", dataSource=").append(dataSource);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}