package com.cetcme.springBootDemo.domain;

import java.io.Serializable;
import java.util.Date;

public class SysConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.SYS_CONFIG_ID
     *
     * @mbggenerated
     */
    private Long sysConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.PARAM_CODE
     *
     * @mbggenerated
     */
    private String paramCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.PARAM_NAME
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.PARAM_VALUE
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.DISP_ORDER
     *
     * @mbggenerated
     */
    private Long dispOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.DEL_FLAG
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.SYS_CONFIG_ID
     *
     * @return the value of t_sys_config.SYS_CONFIG_ID
     *
     * @mbggenerated
     */
    public Long getSysConfigId() {
        return sysConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.SYS_CONFIG_ID
     *
     * @param sysConfigId the value for t_sys_config.SYS_CONFIG_ID
     *
     * @mbggenerated
     */
    public void setSysConfigId(Long sysConfigId) {
        this.sysConfigId = sysConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.PARAM_CODE
     *
     * @return the value of t_sys_config.PARAM_CODE
     *
     * @mbggenerated
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.PARAM_CODE
     *
     * @param paramCode the value for t_sys_config.PARAM_CODE
     *
     * @mbggenerated
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode == null ? null : paramCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.PARAM_NAME
     *
     * @return the value of t_sys_config.PARAM_NAME
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.PARAM_NAME
     *
     * @param paramName the value for t_sys_config.PARAM_NAME
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.PARAM_VALUE
     *
     * @return the value of t_sys_config.PARAM_VALUE
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.PARAM_VALUE
     *
     * @param paramValue the value for t_sys_config.PARAM_VALUE
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.UNIT
     *
     * @return the value of t_sys_config.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.UNIT
     *
     * @param unit the value for t_sys_config.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.MEMO
     *
     * @return the value of t_sys_config.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.MEMO
     *
     * @param memo the value for t_sys_config.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.DISP_ORDER
     *
     * @return the value of t_sys_config.DISP_ORDER
     *
     * @mbggenerated
     */
    public Long getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.DISP_ORDER
     *
     * @param dispOrder the value for t_sys_config.DISP_ORDER
     *
     * @mbggenerated
     */
    public void setDispOrder(Long dispOrder) {
        this.dispOrder = dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.CREATE_USER_ID
     *
     * @return the value of t_sys_config.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.CREATE_USER_ID
     *
     * @param createUserId the value for t_sys_config.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.CREATE_TIME
     *
     * @return the value of t_sys_config.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.CREATE_TIME
     *
     * @param createTime the value for t_sys_config.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.UPDATE_USER_ID
     *
     * @return the value of t_sys_config.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.UPDATE_USER_ID
     *
     * @param updateUserId the value for t_sys_config.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.UPDATE_TIME
     *
     * @return the value of t_sys_config.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.UPDATE_TIME
     *
     * @param updateTime the value for t_sys_config.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.DEL_FLAG
     *
     * @return the value of t_sys_config.DEL_FLAG
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.DEL_FLAG
     *
     * @param delFlag the value for t_sys_config.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_config
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysConfigId=").append(sysConfigId);
        sb.append(", paramCode=").append(paramCode);
        sb.append(", paramName=").append(paramName);
        sb.append(", paramValue=").append(paramValue);
        sb.append(", unit=").append(unit);
        sb.append(", memo=").append(memo);
        sb.append(", dispOrder=").append(dispOrder);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}